// Code generated by accel-kernel. DO NOT EDIT.

package testkernels

import (
	"golang.design/x/accel"
	"golang.design/x/accel/kmath"
)

// ParamsCodec is the generated std140 codec for Params.
//
// The offsets are std140's, not Go's. A caller never spells one.
type ParamsCodec struct{}

// ParamsBlockSize is the encoded size of a Params block, in bytes.
const ParamsBlockSize = 96

// EncodedSize reports the std140 block size.
func (ParamsCodec) EncodedSize() int { return ParamsBlockSize }

// Encode writes value into dst in std140 layout.
func (ParamsCodec) Encode(dst []byte, value Params) error {
	w := accel.NewUniformWriter(dst)
	w.F32(0, value.Scale)
	w.F32(16, value.Origin[0])
	w.F32(20, value.Origin[1])
	w.F32(24, value.Origin[2])
	w.U32(28, value.Steps)
	w.F32(32, value.Inverse[0][0])
	w.F32(36, value.Inverse[0][1])
	w.F32(40, value.Inverse[0][2])
	w.F32(44, value.Inverse[0][3])
	w.F32(48, value.Inverse[1][0])
	w.F32(52, value.Inverse[1][1])
	w.F32(56, value.Inverse[1][2])
	w.F32(60, value.Inverse[1][3])
	w.F32(64, value.Inverse[2][0])
	w.F32(68, value.Inverse[2][1])
	w.F32(72, value.Inverse[2][2])
	w.F32(76, value.Inverse[2][3])
	w.F32(80, value.Inverse[3][0])
	w.F32(84, value.Inverse[3][1])
	w.F32(88, value.Inverse[3][2])
	w.F32(92, value.Inverse[3][3])
	return w.Err()
}

// clampIndexFlat is the generated lowering of the helper clampIndex.
func clampIndexFlat(i uint32, n uint32) uint32 {
	if n == uint32(0) {
		return uint32(0)
	}
	if i >= n {
		return (n - uint32(1))
	}
	return i
}

// accumulateFlat is the generated lowering of the helper accumulate.
func accumulateFlat(in []float32, from uint32, to uint32) float32 {
	var total float32 = float32(0)
	{
		var i uint32 = from
		for ; i < to; i = (i + uint32(1)) {
			total = float32(total + in[i])
		}
	}
	return total
}

// addFlat is the generated flat lowering of Add.
//
// It is what the CPU backend runs. The authored Add is never registered as
// an executable: it supplies the typed source this was built from, and it is
// run only by the test that checks the two agree.
func addFlat(t accel.Thread, a []float32, b []float32, out []float32) {
	var i uint32 = t.GlobalID().X
	if i < uint32(int32(len(out))) {
		out[i] = float32(a[i] + b[i])
	}
}

// AddKernel is the compiled form of Add.
var AddKernel = accel.Kernel{
	Name:          "Add",
	WorkgroupSize: accel.ID3{X: 64, Y: 1, Z: 1},
	Bindings: []accel.KernelBinding{
		{Name: "a", DType: accel.KernelF32, Access: accel.KernelRead},
		{Name: "b", DType: accel.KernelF32, Access: accel.KernelRead},
		{Name: "out", DType: accel.KernelF32, Access: accel.KernelWrite},
	},
	Digest:    "38bab352b11121654f413afaf670a778",
	Generator: accel.KernelABIVersion,
	Flat: func(t accel.Thread, a accel.KernelArgs) {
		addFlat(t, accel.KernelSlice[float32](a, 0), accel.KernelSlice[float32](a, 1), accel.KernelSlice[float32](a, 2))
	},
}

// segmentSumFlat is the generated flat lowering of SegmentSum.
//
// It is what the CPU backend runs. The authored SegmentSum is never registered as
// an executable: it supplies the typed source this was built from, and it is
// run only by the test that checks the two agree.
func segmentSumFlat(t accel.Thread, in []float32, out []float32) {
	var i uint32 = t.GlobalID().X
	var n uint32 = uint32(int32(len(out)))
	if i >= n {
		return
	}
	var width uint32 = uint32(4)
	var from uint32 = clampIndexFlat((i * width), uint32(int32(len(in))))
	var to uint32 = clampIndexFlat((from + width), uint32(int32(len(in))))
	out[i] = accumulateFlat(in, from, to)
}

// SegmentSumKernel is the compiled form of SegmentSum.
var SegmentSumKernel = accel.Kernel{
	Name:          "SegmentSum",
	WorkgroupSize: accel.ID3{X: 32, Y: 1, Z: 1},
	Bindings: []accel.KernelBinding{
		{Name: "in", DType: accel.KernelF32, Access: accel.KernelRead},
		{Name: "out", DType: accel.KernelF32, Access: accel.KernelWrite},
	},
	Digest:    "477e2a9a314673b1a980b020f3dc68ec",
	Generator: accel.KernelABIVersion,
	Flat: func(t accel.Thread, a accel.KernelArgs) {
		segmentSumFlat(t, accel.KernelSlice[float32](a, 0), accel.KernelSlice[float32](a, 1))
	},
}

// countAboveFlat is the generated flat lowering of CountAbove.
//
// It is what the CPU backend runs. The authored CountAbove is never registered as
// an executable: it supplies the typed source this was built from, and it is
// run only by the test that checks the two agree.
func countAboveFlat(t accel.Thread, in []float32, out []int32) {
	var i uint32 = t.GlobalID().X
	if i >= uint32(int32(len(out))) {
		return
	}
	var count int32 = int32(0)
	var limit uint32 = uint32(int32(len(in)))
	{
		var j uint32 = uint32(0)
		for ; j < limit; j = (j + uint32(1)) {
			if in[j] <= float32(0) {
				continue
			}
			count = (count + int32(1))
		}
	}
	var j uint32 = uint32(0)
	for j < limit {
		j = (j + uint32(1))
	}
	for {
		if j >= limit {
			break
		}
		j = (j + uint32(1))
	}
	out[i] = count
}

// CountAboveKernel is the compiled form of CountAbove.
var CountAboveKernel = accel.Kernel{
	Name:          "CountAbove",
	WorkgroupSize: accel.ID3{X: 16, Y: 1, Z: 1},
	Bindings: []accel.KernelBinding{
		{Name: "in", DType: accel.KernelF32, Access: accel.KernelRead},
		{Name: "out", DType: accel.KernelI32, Access: accel.KernelWrite},
	},
	Digest:    "5ad2dbd0fd90561622cedabdd265bd18",
	Generator: accel.KernelABIVersion,
	Flat: func(t accel.Thread, a accel.KernelArgs) {
		countAboveFlat(t, accel.KernelSlice[float32](a, 0), accel.KernelSlice[int32](a, 1))
	},
}

// normalizeFlat is the generated flat lowering of Normalize.
//
// It is what the CPU backend runs. The authored Normalize is never registered as
// an executable: it supplies the typed source this was built from, and it is
// run only by the test that checks the two agree.
func normalizeFlat(t accel.Thread, in []accel.Float16, out []float32, scratch []float32) {
	var i uint32 = t.GlobalID().X
	if i >= uint32(int32(len(out))) {
		return
	}
	var x float32 = in[i].F32()
	var magnitude float32 = kmath.Sqrt(float32(kmath.Abs(x) + float32(1)))
	scratch[i] = magnitude
	out[i] = float32(x * kmath.RSqrt(float32(magnitude*magnitude)))
}

// NormalizeKernel is the compiled form of Normalize.
var NormalizeKernel = accel.Kernel{
	Name:          "Normalize",
	WorkgroupSize: accel.ID3{X: 32, Y: 1, Z: 1},
	Bindings: []accel.KernelBinding{
		{Name: "in", DType: accel.KernelF16, Access: accel.KernelRead},
		{Name: "out", DType: accel.KernelF32, Access: accel.KernelWrite},
		{Name: "scratch", DType: accel.KernelF32, Access: accel.KernelWrite},
	},
	Digest:    "f8dc2fa112e32b880d444e8b40c5dc32",
	Generator: accel.KernelABIVersion,
	Flat: func(t accel.Thread, a accel.KernelArgs) {
		normalizeFlat(t, accel.KernelSlice[accel.Float16](a, 0), accel.KernelSlice[float32](a, 1), accel.KernelSlice[float32](a, 2))
	},
}

// scaleFlat is the generated flat lowering of Scale.
//
// It is what the CPU backend runs. The authored Scale is never registered as
// an executable: it supplies the typed source this was built from, and it is
// run only by the test that checks the two agree.
func scaleFlat(t accel.Thread, in []float32, out []float32) {
	var i uint32 = t.GlobalID().X
	if i < uint32(int32(len(out))) {
		out[i] = float32(in[i] * float32(2))
	}
}

// ScaleKernel is the compiled form of Scale.
var ScaleKernel = accel.Kernel{
	Name:          "Scale",
	WorkgroupSize: accel.ID3{X: 64, Y: 1, Z: 1},
	Bindings: []accel.KernelBinding{
		{Name: "in", DType: accel.KernelF32, Access: accel.KernelRead},
		{Name: "out", DType: accel.KernelF32, Access: accel.KernelWrite},
	},
	Digest:    "90a4e63995b835b3310099c4e49d6b56",
	Generator: accel.KernelABIVersion,
	Flat: func(t accel.Thread, a accel.KernelArgs) {
		scaleFlat(t, accel.KernelSlice[float32](a, 0), accel.KernelSlice[float32](a, 1))
	},
}

// transformFlat is the generated flat lowering of Transform.
//
// It is what the CPU backend runs. The authored Transform is never registered as
// an executable: it supplies the typed source this was built from, and it is
// run only by the test that checks the two agree.
func transformFlat(t accel.Thread, p Params, in []float32, out []float32) {
	var i uint32 = t.GlobalID().X
	if (i >= p.Steps) || (i >= uint32(int32(len(out)))) {
		return
	}
	var acc float32 = (float32(in[i]*p.Scale) + p.Origin[int32(0)])
	{
		var c uint32 = uint32(0)
		for ; c < uint32(4); c = (c + uint32(1)) {
			acc = float32(acc + float32(p.Inverse[c][int32(0)]*p.Origin[int32(1)]))
		}
	}
	out[i] = float32(acc + p.Origin[int32(2)])
}

// TransformKernel is the compiled form of Transform.
var TransformKernel = accel.Kernel{
	Name:          "Transform",
	WorkgroupSize: accel.ID3{X: 32, Y: 1, Z: 1},
	Bindings: []accel.KernelBinding{
		{Name: "in", DType: accel.KernelF32, Access: accel.KernelRead},
		{Name: "out", DType: accel.KernelF32, Access: accel.KernelWrite},
	},
	Digest:    "684924c0e723f6b164d600454328dbee",
	Generator: accel.KernelABIVersion,
	Uniforms: []accel.KernelUniform{
		{Name: "p", Type: "Params", Size: 96},
	},
	Flat: func(t accel.Thread, a accel.KernelArgs) {
		transformFlat(t, accel.KernelUniformValue[Params](a, 0), accel.KernelSlice[float32](a, 0), accel.KernelSlice[float32](a, 1))
	},
}
