// Code generated by accel-kernel. DO NOT EDIT.

package testkernels

import (
	"golang.design/x/accel"
	"golang.design/x/accel/kmath"
	"math"
)

// AttnDimsCodec is the generated std140 codec for AttnDims.
//
// The offsets are std140's, not Go's. A caller never spells one.
type AttnDimsCodec struct{}

// AttnDimsBlockSize is the encoded size of a AttnDims block, in bytes.
const AttnDimsBlockSize = 32

// EncodedSize reports the std140 block size.
func (AttnDimsCodec) EncodedSize() int { return AttnDimsBlockSize }

// Encode writes value into dst in std140 layout.
func (AttnDimsCodec) Encode(dst []byte, value AttnDims) error {
	w := accel.NewUniformWriter(dst)
	w.U32(0, value.QHeads)
	w.U32(4, value.KVHeads)
	w.U32(8, value.HeadDim)
	w.U32(12, value.KVLen)
	w.F32(16, value.Scale)
	return w.Err()
}

// ScaleParamsCodec is the generated std140 codec for ScaleParams.
//
// The offsets are std140's, not Go's. A caller never spells one.
type ScaleParamsCodec struct{}

// ScaleParamsBlockSize is the encoded size of a ScaleParams block, in bytes.
const ScaleParamsBlockSize = 16

// EncodedSize reports the std140 block size.
func (ScaleParamsCodec) EncodedSize() int { return ScaleParamsBlockSize }

// Encode writes value into dst in std140 layout.
func (ScaleParamsCodec) Encode(dst []byte, value ScaleParams) error {
	w := accel.NewUniformWriter(dst)
	w.F32(0, value.Factor)
	return w.Err()
}

// RowParamsCodec is the generated std140 codec for RowParams.
//
// The offsets are std140's, not Go's. A caller never spells one.
type RowParamsCodec struct{}

// RowParamsBlockSize is the encoded size of a RowParams block, in bytes.
const RowParamsBlockSize = 16

// EncodedSize reports the std140 block size.
func (RowParamsCodec) EncodedSize() int { return RowParamsBlockSize }

// Encode writes value into dst in std140 layout.
func (RowParamsCodec) Encode(dst []byte, value RowParams) error {
	w := accel.NewUniformWriter(dst)
	w.U32(0, value.Rows)
	w.U32(4, value.Width)
	w.U32(8, value.Capacity)
	return w.Err()
}

// RoPEParamsCodec is the generated std140 codec for RoPEParams.
//
// The offsets are std140's, not Go's. A caller never spells one.
type RoPEParamsCodec struct{}

// RoPEParamsBlockSize is the encoded size of a RoPEParams block, in bytes.
const RoPEParamsBlockSize = 32

// EncodedSize reports the std140 block size.
func (RoPEParamsCodec) EncodedSize() int { return RoPEParamsBlockSize }

// Encode writes value into dst in std140 layout.
func (RoPEParamsCodec) Encode(dst []byte, value RoPEParams) error {
	w := accel.NewUniformWriter(dst)
	w.U32(0, value.Rows)
	w.U32(4, value.Width)
	w.U32(8, value.RotaryDim)
	w.F32(12, value.Base)
	w.U32(16, value.Offset)
	return w.Err()
}

// GEMMDimsCodec is the generated std140 codec for GEMMDims.
//
// The offsets are std140's, not Go's. A caller never spells one.
type GEMMDimsCodec struct{}

// GEMMDimsBlockSize is the encoded size of a GEMMDims block, in bytes.
const GEMMDimsBlockSize = 16

// EncodedSize reports the std140 block size.
func (GEMMDimsCodec) EncodedSize() int { return GEMMDimsBlockSize }

// Encode writes value into dst in std140 layout.
func (GEMMDimsCodec) Encode(dst []byte, value GEMMDims) error {
	w := accel.NewUniformWriter(dst)
	w.U32(0, value.M)
	w.U32(4, value.N)
	w.U32(8, value.K)
	return w.Err()
}

// RowDimsCodec is the generated std140 codec for RowDims.
//
// The offsets are std140's, not Go's. A caller never spells one.
type RowDimsCodec struct{}

// RowDimsBlockSize is the encoded size of a RowDims block, in bytes.
const RowDimsBlockSize = 16

// EncodedSize reports the std140 block size.
func (RowDimsCodec) EncodedSize() int { return RowDimsBlockSize }

// Encode writes value into dst in std140 layout.
func (RowDimsCodec) Encode(dst []byte, value RowDims) error {
	w := accel.NewUniformWriter(dst)
	w.U32(0, value.Rows)
	w.U32(4, value.Width)
	w.F32(8, value.Eps)
	return w.Err()
}

// ParamsCodec is the generated std140 codec for Params.
//
// The offsets are std140's, not Go's. A caller never spells one.
type ParamsCodec struct{}

// ParamsBlockSize is the encoded size of a Params block, in bytes.
const ParamsBlockSize = 96

// EncodedSize reports the std140 block size.
func (ParamsCodec) EncodedSize() int { return ParamsBlockSize }

// Encode writes value into dst in std140 layout.
func (ParamsCodec) Encode(dst []byte, value Params) error {
	w := accel.NewUniformWriter(dst)
	w.F32(0, value.Scale)
	w.F32(16, value.Origin[0])
	w.F32(20, value.Origin[1])
	w.F32(24, value.Origin[2])
	w.U32(28, value.Steps)
	w.F32(32, value.Inverse[0][0])
	w.F32(36, value.Inverse[0][1])
	w.F32(40, value.Inverse[0][2])
	w.F32(44, value.Inverse[0][3])
	w.F32(48, value.Inverse[1][0])
	w.F32(52, value.Inverse[1][1])
	w.F32(56, value.Inverse[1][2])
	w.F32(60, value.Inverse[1][3])
	w.F32(64, value.Inverse[2][0])
	w.F32(68, value.Inverse[2][1])
	w.F32(72, value.Inverse[2][2])
	w.F32(76, value.Inverse[2][3])
	w.F32(80, value.Inverse[3][0])
	w.F32(84, value.Inverse[3][1])
	w.F32(88, value.Inverse[3][2])
	w.F32(92, value.Inverse[3][3])
	return w.Err()
}

// clampIndexFlat is the generated lowering of the helper clampIndex.
func clampIndexFlat(i uint32, n uint32) uint32 {
	if n == uint32(0) {
		return uint32(0)
	}
	if i >= n {
		return (n - uint32(1))
	}
	return i
}

// accumulateFlat is the generated lowering of the helper accumulate.
func accumulateFlat(in []float32, from uint32, to uint32) float32 {
	var total float32 = float32(0)
	{
		var i uint32 = from
		for ; i < to; i = (i + uint32(1)) {
			total = float32(total + in[i])
		}
	}
	return total
}

// addFlat is the generated flat lowering of Add.
//
// It is what the CPU backend runs. The authored Add is never registered as
// an executable: it supplies the typed source this was built from, and it is
// run only by the test that checks the two agree.
func addFlat(t accel.Thread, a []float32, b []float32, out []float32) {
	var i uint32 = t.GlobalID().X
	if i < uint32(int32(len(out))) {
		out[i] = float32(a[i] + b[i])
	}
}

// AddKernel is the compiled form of Add.
var AddKernel = accel.Kernel{
	Name:          "Add",
	WorkgroupSize: accel.ID3{X: 64, Y: 1, Z: 1},
	Bindings: []accel.KernelBinding{
		{Name: "a", DType: accel.KernelF32, Access: accel.KernelRead},
		{Name: "b", DType: accel.KernelF32, Access: accel.KernelRead},
		{Name: "out", DType: accel.KernelF32, Access: accel.KernelWrite},
	},
	Digest:    "1c1b9102edd59d8a729a05cc1ce492a7",
	Generator: accel.KernelABIVersion,
	MSL: `#include <metal_stdlib>
using namespace metal;
#pragma METAL fp contract(off)

kernel void Add(
    const device float *a [[buffer(0)]],
    const device float *b [[buffer(1)]],
    device float *out [[buffer(2)]],
    constant uint *_lens [[buffer(3)]],
    uint3 _gid [[thread_position_in_grid]],
    uint3 _lid [[thread_position_in_threadgroup]],
    uint3 _wid [[threadgroup_position_in_grid]]) {
    uint i = _gid.x;
    if ((i < uint(int(_lens[2])))) {
        out[i] = (a[i] + b[i]);
    }
}
`,
	Flat: func(t accel.Thread, a accel.KernelArgs) {
		addFlat(t, accel.KernelSlice[float32](a, 0), accel.KernelSlice[float32](a, 1), accel.KernelSlice[float32](a, 2))
	},
}

// histogramFlat is the generated flat lowering of Histogram.
//
// It is what the CPU backend runs. The authored Histogram is never registered as
// an executable: it supplies the typed source this was built from, and it is
// run only by the test that checks the two agree.
func histogramFlat(t accel.Thread, in []float32, counts []uint32) {
	var i uint32 = t.GlobalID().X
	if i < uint32(int32(len(in))) {
		var v float32 = in[i]
		var bucket uint32 = uint32(0)
		if v >= math.Float32frombits(0x3F400000 /* 0.75 */) {
			bucket = uint32(3)
		} else if v >= math.Float32frombits(0x3F000000 /* 0.5 */) {
			bucket = uint32(2)
		} else if v >= math.Float32frombits(0x3E800000 /* 0.25 */) {
			bucket = uint32(1)
		}
		accel.AddU32(counts, bucket, uint32(1))
	}
}

// HistogramKernel is the compiled form of Histogram.
var HistogramKernel = accel.Kernel{
	Name:          "Histogram",
	WorkgroupSize: accel.ID3{X: 64, Y: 1, Z: 1},
	Bindings: []accel.KernelBinding{
		{Name: "in", DType: accel.KernelF32, Access: accel.KernelRead},
		{Name: "counts", DType: accel.KernelU32, Access: accel.KernelRead | accel.KernelWrite},
	},
	Digest:    "42b57e65e7c73a120a31d7b730210649",
	Generator: accel.KernelABIVersion,
	Flat: func(t accel.Thread, a accel.KernelArgs) {
		histogramFlat(t, accel.KernelSlice[float32](a, 0), accel.KernelSlice[uint32](a, 1))
	},
}

// atomicOpsFlat is the generated flat lowering of AtomicOps.
//
// It is what the CPU backend runs. The authored AtomicOps is never registered as
// an executable: it supplies the typed source this was built from, and it is
// run only by the test that checks the two agree.
func atomicOpsFlat(t accel.Thread, state []uint32, prev []uint32) {
	prev[int32(0)] = accel.AddU32(state, uint32(0), uint32(7))
	prev[int32(1)] = accel.SubU32(state, uint32(1), uint32(3))
	prev[int32(2)] = accel.MinU32(state, uint32(2), uint32(5))
	prev[int32(3)] = accel.MaxU32(state, uint32(3), uint32(5))
	prev[int32(4)] = accel.AndU32(state, uint32(4), uint32(15))
	prev[int32(5)] = accel.OrU32(state, uint32(5), uint32(240))
	prev[int32(6)] = accel.XorU32(state, uint32(6), uint32(255))
	prev[int32(7)] = accel.ExchangeU32(state, uint32(7), uint32(42))
	prev[int32(8)] = accel.CompareExchangeU32(state, uint32(8), uint32(1), uint32(99))
	prev[int32(9)] = accel.CompareExchangeU32(state, uint32(9), uint32(1), uint32(99))
}

// AtomicOpsKernel is the compiled form of AtomicOps.
var AtomicOpsKernel = accel.Kernel{
	Name:          "AtomicOps",
	WorkgroupSize: accel.ID3{X: 1, Y: 1, Z: 1},
	Bindings: []accel.KernelBinding{
		{Name: "state", DType: accel.KernelU32, Access: accel.KernelRead | accel.KernelWrite},
		{Name: "prev", DType: accel.KernelU32, Access: accel.KernelWrite},
	},
	Digest:    "1c10a109c329670be02ff7e3902c57f2",
	Generator: accel.KernelABIVersion,
	Flat: func(t accel.Thread, a accel.KernelArgs) {
		atomicOpsFlat(t, accel.KernelSlice[uint32](a, 0), accel.KernelSlice[uint32](a, 1))
	},
}

// countWorkgroupsFlat is the generated flat lowering of CountWorkgroups.
//
// It is what the CPU backend runs. The authored CountWorkgroups is never registered as
// an executable: it supplies the typed source this was built from, and it is
// run only by the test that checks the two agree.
func countWorkgroupsFlat(t accel.Thread, counts []uint32) {
	if t.LocalID().X == uint32(0) {
		accel.AddU32(counts, uint32(0), uint32(1))
	}
}

// CountWorkgroupsKernel is the compiled form of CountWorkgroups.
var CountWorkgroupsKernel = accel.Kernel{
	Name:          "CountWorkgroups",
	WorkgroupSize: accel.ID3{X: 64, Y: 1, Z: 1},
	Bindings: []accel.KernelBinding{
		{Name: "counts", DType: accel.KernelU32, Access: accel.KernelRead | accel.KernelWrite},
	},
	Digest:    "35bc8f6fc0a4a37cb11101cfd89794a8",
	Generator: accel.KernelABIVersion,
	Flat: func(t accel.Thread, a accel.KernelArgs) {
		countWorkgroupsFlat(t, accel.KernelSlice[uint32](a, 0))
	},
}

// attentionDecodeFrame is one invocation's saved state between suspension points.
//
// Every local lives here rather than only those live across a barrier: that
// is a superset of the right answer and therefore correct, and a liveness
// analysis can shrink it later without changing anything a caller sees.
type attentionDecodeFrame struct {
	pc       int
	h0       uint32
	lane1    uint32
	group2   uint32
	kvHead3  uint32
	s4       float32
	acc5     float32
	i6       uint32
	qi7      float32
	ki8      float32
	stride9  uint32
	m10      float32
	e11      float32
	stride12 uint32
	total13  float32
	acc14    float32
	j15      uint32
}

// attentionDecodeCoop runs one invocation of AttentionDecode to its next suspension point.
//
// It reports whether the invocation suspended. False means it finished, and
// the scheduler stops calling it. Each case is one state; the assignment to
// pc before continuing is the jump, which is explicit because a loop's states
// do not run in numeric order.
func attentionDecodeCoop(t accel.Thread, d AttnDims, q []float32, k []float32, v []float32, out []float32, scores *[128]float32, red *[128]float32, f *attentionDecodeFrame, frame *accel.KernelFrame, tr *accel.KernelSharedTracker) bool {
	for {
		switch f.pc {
		case 0:
			f.h0 = t.GroupID().X
			f.lane1 = t.LocalID().X
			f.group2 = (d.QHeads / d.KVHeads)
			f.kvHead3 = (f.h0 / f.group2)
			f.s4 = float32(0)
			if f.lane1 < d.KVLen {
				f.acc5 = float32(0)
				{
					f.i6 = uint32(0)
					for ; f.i6 < d.HeadDim; f.i6 = (f.i6 + uint32(1)) {
						f.qi7 = q[((f.h0 * d.HeadDim) + f.i6)]
						f.ki8 = k[((((f.lane1 * d.KVHeads) * d.HeadDim) + (f.kvHead3 * d.HeadDim)) + f.i6)]
						f.acc5 = float32(f.acc5 + float32(f.qi7*f.ki8))
					}
				}
				f.s4 = float32(f.acc5 * d.Scale)
			}
			tr.Write(0, int(f.lane1))
			scores[f.lane1] = f.s4
			tr.Write(1, int(f.lane1))
			red[f.lane1] = f.s4
			if f.lane1 >= d.KVLen {
				tr.Write(1, int(f.lane1))
				red[f.lane1] = math.Float32frombits(0xFF7FC99E /* -3.4e+38 */)
			}
			f.pc = 1
			continue
		case 1:
			f.pc = 2
			frame.Barrier = accel.KernelBarrierID{Index: 1, Pos: "attention.go:94:2"}
			return true
		case 2:
			f.stride9 = uint32(64)
			f.pc = 6
			continue
		case 3:
			if f.lane1 < f.stride9 {
				tr.Write(1, int(f.lane1))
				red[f.lane1] = kmath.Max(red[tr.ReadAt(1, int(f.lane1))], red[tr.ReadAt(1, int((f.lane1+f.stride9)))])
			}
			f.pc = 4
			continue
		case 4:
			f.pc = 5
			frame.Barrier = accel.KernelBarrierID{Index: 4, Pos: "attention.go:100:3"}
			return true
		case 5:
			f.stride9 = (f.stride9 / uint32(2))
			f.pc = 6
			continue
		case 6:
			if f.stride9 > uint32(0) {
				f.pc = 3
				continue
			}
			f.pc = 7
			continue
		case 7:
			f.m10 = red[tr.ReadAt(1, int(int32(0)))]
			f.pc = 8
			continue
		case 8:
			f.pc = 9
			frame.Barrier = accel.KernelBarrierID{Index: 8, Pos: "attention.go:103:2"}
			return true
		case 9:
			f.e11 = float32(0)
			if f.lane1 < d.KVLen {
				f.e11 = kmath.Exp(float32(scores[tr.ReadAt(0, int(f.lane1))] - f.m10))
			}
			tr.Write(0, int(f.lane1))
			scores[f.lane1] = f.e11
			tr.Write(1, int(f.lane1))
			red[f.lane1] = f.e11
			f.pc = 10
			continue
		case 10:
			f.pc = 11
			frame.Barrier = accel.KernelBarrierID{Index: 10, Pos: "attention.go:114:2"}
			return true
		case 11:
			f.stride12 = uint32(64)
			f.pc = 15
			continue
		case 12:
			if f.lane1 < f.stride12 {
				tr.Write(1, int(f.lane1))
				red[f.lane1] = float32(red[tr.ReadAt(1, int(f.lane1))] + red[tr.ReadAt(1, int((f.lane1+f.stride12)))])
			}
			f.pc = 13
			continue
		case 13:
			f.pc = 14
			frame.Barrier = accel.KernelBarrierID{Index: 13, Pos: "attention.go:120:3"}
			return true
		case 14:
			f.stride12 = (f.stride12 / uint32(2))
			f.pc = 15
			continue
		case 15:
			if f.stride12 > uint32(0) {
				f.pc = 12
				continue
			}
			f.pc = 16
			continue
		case 16:
			f.total13 = red[tr.ReadAt(1, int(int32(0)))]
			if f.lane1 < d.HeadDim {
				f.acc14 = float32(0)
				{
					f.j15 = uint32(0)
					for ; f.j15 < d.KVLen; f.j15 = (f.j15 + uint32(1)) {
						f.acc14 = float32(f.acc14 + float32(scores[tr.ReadAt(0, int(f.j15))]*v[((((f.j15*d.KVHeads)*d.HeadDim)+(f.kvHead3*d.HeadDim))+f.lane1)]))
					}
				}
				out[((f.h0 * d.HeadDim) + f.lane1)] = float32(f.acc14 / f.total13)
			}
			return false
		}
		return false
	}
}

// AttentionDecodeKernel is the compiled form of AttentionDecode.
var AttentionDecodeKernel = accel.Kernel{
	Name:          "AttentionDecode",
	WorkgroupSize: accel.ID3{X: 128, Y: 1, Z: 1},
	Bindings: []accel.KernelBinding{
		{Name: "q", DType: accel.KernelF32, Access: accel.KernelRead},
		{Name: "k", DType: accel.KernelF32, Access: accel.KernelRead},
		{Name: "v", DType: accel.KernelF32, Access: accel.KernelRead},
		{Name: "out", DType: accel.KernelF32, Access: accel.KernelWrite},
	},
	Digest:      "17c3c7d2b180f4ed260f0323f8dad89a",
	Generator:   accel.KernelABIVersion,
	Suspensions: 5,
	SharedSizes: []int{128, 128},
	NewShared: func() []any {
		var s0 [128]float32
		accel.KernelPoison(s0[:])
		var s1 [128]float32
		accel.KernelPoison(s1[:])
		return []any{&s0, &s1}
	},
	Uniforms: []accel.KernelUniform{
		{Name: "d", Type: "AttnDims", Size: 32, Encode: func(dst []byte, v any) error {
			return accel.EncodeKernelUniform(dst, v, AttnDimsCodec{}.Encode)
		}},
	},
	Cooperative: func(t accel.Thread, a accel.KernelArgs, slot *accel.KernelFrame) bool {
		f, _ := slot.State.(*attentionDecodeFrame)
		if f == nil {
			f = &attentionDecodeFrame{}
			slot.State = f
		}
		return attentionDecodeCoop(t, accel.KernelUniformValue[AttnDims](a, 0), accel.KernelSlice[float32](a, 0), accel.KernelSlice[float32](a, 1), accel.KernelSlice[float32](a, 2), accel.KernelSlice[float32](a, 3), accel.KernelShared[[128]float32](a, 0), accel.KernelShared[[128]float32](a, 1), f, slot, slot.Shared)
	},
}

// exchangeFrame is one invocation's saved state between suspension points.
//
// Every local lives here rather than only those live across a barrier: that
// is a superset of the right answer and therefore correct, and a liveness
// analysis can shrink it later without changing anything a caller sees.
type exchangeFrame struct {
	pc    int
	lid0  uint32
	gid1  uint32
	next2 uint32
}

// exchangeCoop runs one invocation of Exchange to its next suspension point.
//
// It reports whether the invocation suspended. False means it finished, and
// the scheduler stops calling it. Each case is one state; the assignment to
// pc before continuing is the jump, which is explicit because a loop's states
// do not run in numeric order.
func exchangeCoop(t accel.Thread, in []float32, out []float32, sh *[64]float32, f *exchangeFrame, frame *accel.KernelFrame, tr *accel.KernelSharedTracker) bool {
	for {
		switch f.pc {
		case 0:
			f.lid0 = t.LocalID().X
			f.gid1 = t.GlobalID().X
			tr.Write(0, int(f.lid0))
			sh[f.lid0] = in[f.gid1]
			f.pc = 1
			continue
		case 1:
			f.pc = 2
			frame.Barrier = accel.KernelBarrierID{Index: 1, Pos: "coop.go:30:2"}
			return true
		case 2:
			f.next2 = (f.lid0 + uint32(1))
			if f.next2 == uint32(64) {
				f.next2 = uint32(0)
			}
			if f.gid1 < uint32(int32(len(out))) {
				out[f.gid1] = sh[tr.ReadAt(0, int(f.next2))]
			}
			return false
		}
		return false
	}
}

// ExchangeKernel is the compiled form of Exchange.
var ExchangeKernel = accel.Kernel{
	Name:          "Exchange",
	WorkgroupSize: accel.ID3{X: 64, Y: 1, Z: 1},
	Bindings: []accel.KernelBinding{
		{Name: "in", DType: accel.KernelF32, Access: accel.KernelRead},
		{Name: "out", DType: accel.KernelF32, Access: accel.KernelWrite},
	},
	Digest:      "8fbafe502892895a36d26b891966beee",
	Generator:   accel.KernelABIVersion,
	Suspensions: 1,
	SharedSizes: []int{64},
	NewShared: func() []any {
		var s0 [64]float32
		accel.KernelPoison(s0[:])
		return []any{&s0}
	},
	Cooperative: func(t accel.Thread, a accel.KernelArgs, slot *accel.KernelFrame) bool {
		f, _ := slot.State.(*exchangeFrame)
		if f == nil {
			f = &exchangeFrame{}
			slot.State = f
		}
		return exchangeCoop(t, accel.KernelSlice[float32](a, 0), accel.KernelSlice[float32](a, 1), accel.KernelShared[[64]float32](a, 0), f, slot, slot.Shared)
	},
}

// reduceLoopFrame is one invocation's saved state between suspension points.
//
// Every local lives here rather than only those live across a barrier: that
// is a superset of the right answer and therefore correct, and a liveness
// analysis can shrink it later without changing anything a caller sees.
type reduceLoopFrame struct {
	pc      int
	lid0    uint32
	gid1    uint32
	stride2 uint32
}

// reduceLoopCoop runs one invocation of ReduceLoop to its next suspension point.
//
// It reports whether the invocation suspended. False means it finished, and
// the scheduler stops calling it. Each case is one state; the assignment to
// pc before continuing is the jump, which is explicit because a loop's states
// do not run in numeric order.
func reduceLoopCoop(t accel.Thread, in []float32, out []float32, sh *[64]float32, f *reduceLoopFrame, frame *accel.KernelFrame, tr *accel.KernelSharedTracker) bool {
	for {
		switch f.pc {
		case 0:
			f.lid0 = t.LocalID().X
			f.gid1 = t.GlobalID().X
			tr.Write(0, int(f.lid0))
			sh[f.lid0] = in[f.gid1]
			f.pc = 1
			continue
		case 1:
			f.pc = 2
			frame.Barrier = accel.KernelBarrierID{Index: 1, Pos: "coop.go:56:2"}
			return true
		case 2:
			f.stride2 = uint32(32)
			f.pc = 6
			continue
		case 3:
			if f.lid0 < f.stride2 {
				tr.Write(0, int(f.lid0))
				sh[f.lid0] = float32(sh[tr.ReadAt(0, int(f.lid0))] + sh[tr.ReadAt(0, int((f.lid0+f.stride2)))])
			}
			f.pc = 4
			continue
		case 4:
			f.pc = 5
			frame.Barrier = accel.KernelBarrierID{Index: 4, Pos: "coop.go:62:3"}
			return true
		case 5:
			f.stride2 = (f.stride2 / uint32(2))
			f.pc = 6
			continue
		case 6:
			if f.stride2 > uint32(0) {
				f.pc = 3
				continue
			}
			f.pc = 7
			continue
		case 7:
			if f.lid0 == uint32(0) {
				out[t.GroupID().X] = sh[tr.ReadAt(0, int(int32(0)))]
			}
			return false
		}
		return false
	}
}

// ReduceLoopKernel is the compiled form of ReduceLoop.
var ReduceLoopKernel = accel.Kernel{
	Name:          "ReduceLoop",
	WorkgroupSize: accel.ID3{X: 64, Y: 1, Z: 1},
	Bindings: []accel.KernelBinding{
		{Name: "in", DType: accel.KernelF32, Access: accel.KernelRead},
		{Name: "out", DType: accel.KernelF32, Access: accel.KernelWrite},
	},
	Digest:      "cd47629a5d0b137a4eb63cfe66e87bf2",
	Generator:   accel.KernelABIVersion,
	Suspensions: 2,
	SharedSizes: []int{64},
	NewShared: func() []any {
		var s0 [64]float32
		accel.KernelPoison(s0[:])
		return []any{&s0}
	},
	Cooperative: func(t accel.Thread, a accel.KernelArgs, slot *accel.KernelFrame) bool {
		f, _ := slot.State.(*reduceLoopFrame)
		if f == nil {
			f = &reduceLoopFrame{}
			slot.State = f
		}
		return reduceLoopCoop(t, accel.KernelSlice[float32](a, 0), accel.KernelSlice[float32](a, 1), accel.KernelShared[[64]float32](a, 0), f, slot, slot.Shared)
	},
}

// reduceUnrolledFrame is one invocation's saved state between suspension points.
//
// Every local lives here rather than only those live across a barrier: that
// is a superset of the right answer and therefore correct, and a liveness
// analysis can shrink it later without changing anything a caller sees.
type reduceUnrolledFrame struct {
	pc   int
	lid0 uint32
	gid1 uint32
}

// reduceUnrolledCoop runs one invocation of ReduceUnrolled to its next suspension point.
//
// It reports whether the invocation suspended. False means it finished, and
// the scheduler stops calling it. Each case is one state; the assignment to
// pc before continuing is the jump, which is explicit because a loop's states
// do not run in numeric order.
func reduceUnrolledCoop(t accel.Thread, in []float32, out []float32, sh *[64]float32, f *reduceUnrolledFrame, frame *accel.KernelFrame, tr *accel.KernelSharedTracker) bool {
	for {
		switch f.pc {
		case 0:
			f.lid0 = t.LocalID().X
			f.gid1 = t.GlobalID().X
			tr.Write(0, int(f.lid0))
			sh[f.lid0] = in[f.gid1]
			f.pc = 1
			continue
		case 1:
			f.pc = 2
			frame.Barrier = accel.KernelBarrierID{Index: 1, Pos: "coop.go:83:2"}
			return true
		case 2:
			if f.lid0 < uint32(32) {
				tr.Write(0, int(f.lid0))
				sh[f.lid0] = float32(sh[tr.ReadAt(0, int(f.lid0))] + sh[tr.ReadAt(0, int((f.lid0+uint32(32))))])
			}
			f.pc = 3
			continue
		case 3:
			f.pc = 4
			frame.Barrier = accel.KernelBarrierID{Index: 3, Pos: "coop.go:88:2"}
			return true
		case 4:
			if f.lid0 < uint32(16) {
				tr.Write(0, int(f.lid0))
				sh[f.lid0] = float32(sh[tr.ReadAt(0, int(f.lid0))] + sh[tr.ReadAt(0, int((f.lid0+uint32(16))))])
			}
			f.pc = 5
			continue
		case 5:
			f.pc = 6
			frame.Barrier = accel.KernelBarrierID{Index: 5, Pos: "coop.go:92:2"}
			return true
		case 6:
			if f.lid0 < uint32(8) {
				tr.Write(0, int(f.lid0))
				sh[f.lid0] = float32(sh[tr.ReadAt(0, int(f.lid0))] + sh[tr.ReadAt(0, int((f.lid0+uint32(8))))])
			}
			f.pc = 7
			continue
		case 7:
			f.pc = 8
			frame.Barrier = accel.KernelBarrierID{Index: 7, Pos: "coop.go:96:2"}
			return true
		case 8:
			if f.lid0 < uint32(4) {
				tr.Write(0, int(f.lid0))
				sh[f.lid0] = float32(sh[tr.ReadAt(0, int(f.lid0))] + sh[tr.ReadAt(0, int((f.lid0+uint32(4))))])
			}
			f.pc = 9
			continue
		case 9:
			f.pc = 10
			frame.Barrier = accel.KernelBarrierID{Index: 9, Pos: "coop.go:100:2"}
			return true
		case 10:
			if f.lid0 < uint32(2) {
				tr.Write(0, int(f.lid0))
				sh[f.lid0] = float32(sh[tr.ReadAt(0, int(f.lid0))] + sh[tr.ReadAt(0, int((f.lid0+uint32(2))))])
			}
			f.pc = 11
			continue
		case 11:
			f.pc = 12
			frame.Barrier = accel.KernelBarrierID{Index: 11, Pos: "coop.go:104:2"}
			return true
		case 12:
			if f.lid0 < uint32(1) {
				tr.Write(0, int(f.lid0))
				sh[f.lid0] = float32(sh[tr.ReadAt(0, int(f.lid0))] + sh[tr.ReadAt(0, int((f.lid0+uint32(1))))])
			}
			f.pc = 13
			continue
		case 13:
			f.pc = 14
			frame.Barrier = accel.KernelBarrierID{Index: 13, Pos: "coop.go:108:2"}
			return true
		case 14:
			if f.lid0 == uint32(0) {
				out[t.GroupID().X] = sh[tr.ReadAt(0, int(int32(0)))]
			}
			return false
		}
		return false
	}
}

// ReduceUnrolledKernel is the compiled form of ReduceUnrolled.
var ReduceUnrolledKernel = accel.Kernel{
	Name:          "ReduceUnrolled",
	WorkgroupSize: accel.ID3{X: 64, Y: 1, Z: 1},
	Bindings: []accel.KernelBinding{
		{Name: "in", DType: accel.KernelF32, Access: accel.KernelRead},
		{Name: "out", DType: accel.KernelF32, Access: accel.KernelWrite},
	},
	Digest:      "872f9717e7294bd520cda7ef38cd4b34",
	Generator:   accel.KernelABIVersion,
	Suspensions: 7,
	SharedSizes: []int{64},
	NewShared: func() []any {
		var s0 [64]float32
		accel.KernelPoison(s0[:])
		return []any{&s0}
	},
	Cooperative: func(t accel.Thread, a accel.KernelArgs, slot *accel.KernelFrame) bool {
		f, _ := slot.State.(*reduceUnrolledFrame)
		if f == nil {
			f = &reduceUnrolledFrame{}
			slot.State = f
		}
		return reduceUnrolledCoop(t, accel.KernelSlice[float32](a, 0), accel.KernelSlice[float32](a, 1), accel.KernelShared[[64]float32](a, 0), f, slot, slot.Shared)
	},
}

// elemAddFlat is the generated flat lowering of ElemAdd.
//
// It is what the CPU backend runs. The authored ElemAdd is never registered as
// an executable: it supplies the typed source this was built from, and it is
// run only by the test that checks the two agree.
func elemAddFlat(t accel.Thread, a []float32, b []float32, out []float32) {
	var i uint32 = t.GlobalID().X
	if i < uint32(int32(len(out))) {
		out[i] = float32(a[i] + b[i])
	}
}

// ElemAddKernel is the compiled form of ElemAdd.
var ElemAddKernel = accel.Kernel{
	Name:          "ElemAdd",
	WorkgroupSize: accel.ID3{X: 64, Y: 1, Z: 1},
	Bindings: []accel.KernelBinding{
		{Name: "a", DType: accel.KernelF32, Access: accel.KernelRead},
		{Name: "b", DType: accel.KernelF32, Access: accel.KernelRead},
		{Name: "out", DType: accel.KernelF32, Access: accel.KernelWrite},
	},
	Digest:    "db905a9cd0b2f507c3c362acea42bd2d",
	Generator: accel.KernelABIVersion,
	MSL: `#include <metal_stdlib>
using namespace metal;
#pragma METAL fp contract(off)

kernel void ElemAdd(
    const device float *a [[buffer(0)]],
    const device float *b [[buffer(1)]],
    device float *out [[buffer(2)]],
    constant uint *_lens [[buffer(3)]],
    uint3 _gid [[thread_position_in_grid]],
    uint3 _lid [[thread_position_in_threadgroup]],
    uint3 _wid [[threadgroup_position_in_grid]]) {
    uint i = _gid.x;
    if ((i < uint(int(_lens[2])))) {
        out[i] = (a[i] + b[i]);
    }
}
`,
	Flat: func(t accel.Thread, a accel.KernelArgs) {
		elemAddFlat(t, accel.KernelSlice[float32](a, 0), accel.KernelSlice[float32](a, 1), accel.KernelSlice[float32](a, 2))
	},
}

// elemMulFlat is the generated flat lowering of ElemMul.
//
// It is what the CPU backend runs. The authored ElemMul is never registered as
// an executable: it supplies the typed source this was built from, and it is
// run only by the test that checks the two agree.
func elemMulFlat(t accel.Thread, a []float32, b []float32, out []float32) {
	var i uint32 = t.GlobalID().X
	if i < uint32(int32(len(out))) {
		out[i] = float32(a[i] * b[i])
	}
}

// ElemMulKernel is the compiled form of ElemMul.
var ElemMulKernel = accel.Kernel{
	Name:          "ElemMul",
	WorkgroupSize: accel.ID3{X: 64, Y: 1, Z: 1},
	Bindings: []accel.KernelBinding{
		{Name: "a", DType: accel.KernelF32, Access: accel.KernelRead},
		{Name: "b", DType: accel.KernelF32, Access: accel.KernelRead},
		{Name: "out", DType: accel.KernelF32, Access: accel.KernelWrite},
	},
	Digest:    "f800ffb1b09a78515a2188a92dabb07e",
	Generator: accel.KernelABIVersion,
	MSL: `#include <metal_stdlib>
using namespace metal;
#pragma METAL fp contract(off)

kernel void ElemMul(
    const device float *a [[buffer(0)]],
    const device float *b [[buffer(1)]],
    device float *out [[buffer(2)]],
    constant uint *_lens [[buffer(3)]],
    uint3 _gid [[thread_position_in_grid]],
    uint3 _lid [[thread_position_in_threadgroup]],
    uint3 _wid [[threadgroup_position_in_grid]]) {
    uint i = _gid.x;
    if ((i < uint(int(_lens[2])))) {
        out[i] = (a[i] * b[i]);
    }
}
`,
	Flat: func(t accel.Thread, a accel.KernelArgs) {
		elemMulFlat(t, accel.KernelSlice[float32](a, 0), accel.KernelSlice[float32](a, 1), accel.KernelSlice[float32](a, 2))
	},
}

// elemScaleFlat is the generated flat lowering of ElemScale.
//
// It is what the CPU backend runs. The authored ElemScale is never registered as
// an executable: it supplies the typed source this was built from, and it is
// run only by the test that checks the two agree.
func elemScaleFlat(t accel.Thread, p ScaleParams, in []float32, out []float32) {
	var i uint32 = t.GlobalID().X
	if i < uint32(int32(len(out))) {
		out[i] = float32(in[i] * p.Factor)
	}
}

// ElemScaleKernel is the compiled form of ElemScale.
var ElemScaleKernel = accel.Kernel{
	Name:          "ElemScale",
	WorkgroupSize: accel.ID3{X: 64, Y: 1, Z: 1},
	Bindings: []accel.KernelBinding{
		{Name: "in", DType: accel.KernelF32, Access: accel.KernelRead},
		{Name: "out", DType: accel.KernelF32, Access: accel.KernelWrite},
	},
	Digest:    "d51f4cc1f4fdd6125d6c6e7f233fcbaa",
	Generator: accel.KernelABIVersion,
	MSL: `#include <metal_stdlib>
using namespace metal;
#pragma METAL fp contract(off)

struct ScaleParams {
    float Factor;
    char _tail[12];
};

kernel void ElemScale(
    const device float *in [[buffer(0)]],
    device float *out [[buffer(1)]],
    constant uint *_lens [[buffer(2)]],
    constant ScaleParams &p [[buffer(3)]],
    uint3 _gid [[thread_position_in_grid]],
    uint3 _lid [[thread_position_in_threadgroup]],
    uint3 _wid [[threadgroup_position_in_grid]]) {
    uint i = _gid.x;
    if ((i < uint(int(_lens[1])))) {
        out[i] = (in[i] * p.Factor);
    }
}
`,
	Uniforms: []accel.KernelUniform{
		{Name: "p", Type: "ScaleParams", Size: 16, Encode: func(dst []byte, v any) error {
			return accel.EncodeKernelUniform(dst, v, ScaleParamsCodec{}.Encode)
		}},
	},
	Flat: func(t accel.Thread, a accel.KernelArgs) {
		elemScaleFlat(t, accel.KernelUniformValue[ScaleParams](a, 0), accel.KernelSlice[float32](a, 0), accel.KernelSlice[float32](a, 1))
	},
}

// siLUFlat is the generated flat lowering of SiLU.
//
// It is what the CPU backend runs. The authored SiLU is never registered as
// an executable: it supplies the typed source this was built from, and it is
// run only by the test that checks the two agree.
func siLUFlat(t accel.Thread, in []float32, out []float32) {
	var i uint32 = t.GlobalID().X
	if i < uint32(int32(len(out))) {
		var x float32 = in[i]
		out[i] = float32(x / float32(float32(1)+kmath.Exp(float32(-x))))
	}
}

// SiLUKernel is the compiled form of SiLU.
var SiLUKernel = accel.Kernel{
	Name:          "SiLU",
	WorkgroupSize: accel.ID3{X: 64, Y: 1, Z: 1},
	Bindings: []accel.KernelBinding{
		{Name: "in", DType: accel.KernelF32, Access: accel.KernelRead},
		{Name: "out", DType: accel.KernelF32, Access: accel.KernelWrite},
	},
	Digest:    "260f5b481c75af9c97c7b340e26e6801",
	Generator: accel.KernelABIVersion,
	Flat: func(t accel.Thread, a accel.KernelArgs) {
		siLUFlat(t, accel.KernelSlice[float32](a, 0), accel.KernelSlice[float32](a, 1))
	},
}

// swiGLUFlat is the generated flat lowering of SwiGLU.
//
// It is what the CPU backend runs. The authored SwiGLU is never registered as
// an executable: it supplies the typed source this was built from, and it is
// run only by the test that checks the two agree.
func swiGLUFlat(t accel.Thread, a []float32, b []float32, out []float32) {
	var i uint32 = t.GlobalID().X
	if i < uint32(int32(len(out))) {
		var x float32 = a[i]
		out[i] = float32(float32(x/float32(float32(1)+kmath.Exp(float32(-x)))) * b[i])
	}
}

// SwiGLUKernel is the compiled form of SwiGLU.
var SwiGLUKernel = accel.Kernel{
	Name:          "SwiGLU",
	WorkgroupSize: accel.ID3{X: 64, Y: 1, Z: 1},
	Bindings: []accel.KernelBinding{
		{Name: "a", DType: accel.KernelF32, Access: accel.KernelRead},
		{Name: "b", DType: accel.KernelF32, Access: accel.KernelRead},
		{Name: "out", DType: accel.KernelF32, Access: accel.KernelWrite},
	},
	Digest:    "902706f2e1040486de21a358cda4fc8c",
	Generator: accel.KernelABIVersion,
	Flat: func(t accel.Thread, a accel.KernelArgs) {
		swiGLUFlat(t, accel.KernelSlice[float32](a, 0), accel.KernelSlice[float32](a, 1), accel.KernelSlice[float32](a, 2))
	},
}

// gatherRowsFlat is the generated flat lowering of GatherRows.
//
// It is what the CPU backend runs. The authored GatherRows is never registered as
// an executable: it supplies the typed source this was built from, and it is
// run only by the test that checks the two agree.
func gatherRowsFlat(t accel.Thread, p RowParams, table []float32, ids []uint32, out []float32) {
	var i uint32 = t.GlobalID().X
	if i < (p.Rows * p.Width) {
		var r uint32 = (i / p.Width)
		var c uint32 = (i % p.Width)
		var id uint32 = ids[r]
		if id < p.Capacity {
			out[i] = table[((id * p.Width) + c)]
		} else {
			out[i] = float32(0)
		}
	}
}

// GatherRowsKernel is the compiled form of GatherRows.
var GatherRowsKernel = accel.Kernel{
	Name:          "GatherRows",
	WorkgroupSize: accel.ID3{X: 64, Y: 1, Z: 1},
	Bindings: []accel.KernelBinding{
		{Name: "table", DType: accel.KernelF32, Access: accel.KernelRead},
		{Name: "ids", DType: accel.KernelU32, Access: accel.KernelRead},
		{Name: "out", DType: accel.KernelF32, Access: accel.KernelWrite},
	},
	Digest:    "7dac4797a9bf56ddbcf0466ada474fd9",
	Generator: accel.KernelABIVersion,
	MSL: `#include <metal_stdlib>
using namespace metal;
#pragma METAL fp contract(off)

struct RowParams {
    uint Rows;
    uint Width;
    uint Capacity;
    char _tail[4];
};

kernel void GatherRows(
    const device float *table [[buffer(0)]],
    const device uint *ids [[buffer(1)]],
    device float *out [[buffer(2)]],
    constant uint *_lens [[buffer(3)]],
    constant RowParams &p [[buffer(4)]],
    uint3 _gid [[thread_position_in_grid]],
    uint3 _lid [[thread_position_in_threadgroup]],
    uint3 _wid [[threadgroup_position_in_grid]]) {
    uint i = _gid.x;
    if ((i < (p.Rows * p.Width))) {
        uint r = (i / p.Width);
        uint c = (i % p.Width);
        uint id = ids[r];
        if ((id < p.Capacity)) {
            out[i] = table[((id * p.Width) + c)];
        } else {
            out[i] = float(0);
        }
    }
}
`,
	Uniforms: []accel.KernelUniform{
		{Name: "p", Type: "RowParams", Size: 16, Encode: func(dst []byte, v any) error {
			return accel.EncodeKernelUniform(dst, v, RowParamsCodec{}.Encode)
		}},
	},
	Flat: func(t accel.Thread, a accel.KernelArgs) {
		gatherRowsFlat(t, accel.KernelUniformValue[RowParams](a, 0), accel.KernelSlice[float32](a, 0), accel.KernelSlice[uint32](a, 1), accel.KernelSlice[float32](a, 2))
	},
}

// scatterRowsFlat is the generated flat lowering of ScatterRows.
//
// It is what the CPU backend runs. The authored ScatterRows is never registered as
// an executable: it supplies the typed source this was built from, and it is
// run only by the test that checks the two agree.
func scatterRowsFlat(t accel.Thread, p RowParams, rows []float32, ids []uint32, state []float32) {
	var i uint32 = t.GlobalID().X
	if i < (p.Rows * p.Width) {
		var r uint32 = (i / p.Width)
		var c uint32 = (i % p.Width)
		var id uint32 = ids[r]
		if id < p.Capacity {
			state[((id * p.Width) + c)] = rows[i]
		}
	}
}

// ScatterRowsKernel is the compiled form of ScatterRows.
var ScatterRowsKernel = accel.Kernel{
	Name:          "ScatterRows",
	WorkgroupSize: accel.ID3{X: 64, Y: 1, Z: 1},
	Bindings: []accel.KernelBinding{
		{Name: "rows", DType: accel.KernelF32, Access: accel.KernelRead},
		{Name: "ids", DType: accel.KernelU32, Access: accel.KernelRead},
		{Name: "state", DType: accel.KernelF32, Access: accel.KernelWrite},
	},
	Digest:    "d142c44fe6d877d65140eea9b811c263",
	Generator: accel.KernelABIVersion,
	MSL: `#include <metal_stdlib>
using namespace metal;
#pragma METAL fp contract(off)

struct RowParams {
    uint Rows;
    uint Width;
    uint Capacity;
    char _tail[4];
};

kernel void ScatterRows(
    const device float *rows [[buffer(0)]],
    const device uint *ids [[buffer(1)]],
    device float *state [[buffer(2)]],
    constant uint *_lens [[buffer(3)]],
    constant RowParams &p [[buffer(4)]],
    uint3 _gid [[thread_position_in_grid]],
    uint3 _lid [[thread_position_in_threadgroup]],
    uint3 _wid [[threadgroup_position_in_grid]]) {
    uint i = _gid.x;
    if ((i < (p.Rows * p.Width))) {
        uint r = (i / p.Width);
        uint c = (i % p.Width);
        uint id = ids[r];
        if ((id < p.Capacity)) {
            state[((id * p.Width) + c)] = rows[i];
        }
    }
}
`,
	Uniforms: []accel.KernelUniform{
		{Name: "p", Type: "RowParams", Size: 16, Encode: func(dst []byte, v any) error {
			return accel.EncodeKernelUniform(dst, v, RowParamsCodec{}.Encode)
		}},
	},
	Flat: func(t accel.Thread, a accel.KernelArgs) {
		scatterRowsFlat(t, accel.KernelUniformValue[RowParams](a, 0), accel.KernelSlice[float32](a, 0), accel.KernelSlice[uint32](a, 1), accel.KernelSlice[float32](a, 2))
	},
}

// roPEFlat is the generated flat lowering of RoPE.
//
// It is what the CPU backend runs. The authored RoPE is never registered as
// an executable: it supplies the typed source this was built from, and it is
// run only by the test that checks the two agree.
func roPEFlat(t accel.Thread, p RoPEParams, inout []float32) {
	var i uint32 = t.GlobalID().X
	var pairs uint32 = (p.RotaryDim / uint32(2))
	if i < (p.Rows * pairs) {
		var r uint32 = (i / pairs)
		var k uint32 = (i % pairs)
		var pos float32 = float32((r + p.Offset))
		var exponent float32 = (float32(float32(-2)*float32(k)) / float32(p.RotaryDim))
		var freq float32 = kmath.Exp(float32(exponent * kmath.Log(p.Base)))
		var theta float32 = (pos * freq)
		var c float32 = kmath.Cos(theta)
		var s float32 = kmath.Sin(theta)
		var lo uint32 = ((r * p.Width) + (uint32(2) * k))
		var hi uint32 = (lo + uint32(1))
		var x float32 = inout[lo]
		var y float32 = inout[hi]
		inout[lo] = float32(float32(x*c) - float32(y*s))
		inout[hi] = float32(float32(x*s) + float32(y*c))
	}
}

// RoPEKernel is the compiled form of RoPE.
var RoPEKernel = accel.Kernel{
	Name:          "RoPE",
	WorkgroupSize: accel.ID3{X: 64, Y: 1, Z: 1},
	Bindings: []accel.KernelBinding{
		{Name: "inout", DType: accel.KernelF32, Access: accel.KernelRead | accel.KernelWrite},
	},
	Digest:    "fee80830a38fdfe6fe8a54127cac61a5",
	Generator: accel.KernelABIVersion,
	Uniforms: []accel.KernelUniform{
		{Name: "p", Type: "RoPEParams", Size: 32, Encode: func(dst []byte, v any) error {
			return accel.EncodeKernelUniform(dst, v, RoPEParamsCodec{}.Encode)
		}},
	},
	Flat: func(t accel.Thread, a accel.KernelArgs) {
		roPEFlat(t, accel.KernelUniformValue[RoPEParams](a, 0), accel.KernelSlice[float32](a, 0))
	},
}

// matMulTiledFrame is one invocation's saved state between suspension points.
//
// Every local lives here rather than only those live across a barrier: that
// is a superset of the right answer and therefore correct, and a liveness
// analysis can shrink it later without changing anything a caller sees.
type matMulTiledFrame struct {
	pc    int
	lx0   uint32
	ly1   uint32
	tid2  uint32
	row3  uint32
	col4  uint32
	acc5  float32
	zero6 accel.Float16
	k07   uint32
	kk8   uint32
	nn9   uint32
	kk210 uint32
	k11   uint32
	av12  float32
	bv13  float32
}

// matMulTiledCoop runs one invocation of MatMulTiled to its next suspension point.
//
// It reports whether the invocation suspended. False means it finished, and
// the scheduler stops calling it. Each case is one state; the assignment to
// pc before continuing is the jump, which is explicit because a loop's states
// do not run in numeric order.
func matMulTiledCoop(t accel.Thread, d GEMMDims, a []accel.Float16, b []accel.Float16, out []float32, tileA *[128]accel.Float16, tileB *[256]accel.Float16, f *matMulTiledFrame, frame *accel.KernelFrame, tr *accel.KernelSharedTracker) bool {
	for {
		switch f.pc {
		case 0:
			f.lx0 = t.LocalID().X
			f.ly1 = t.LocalID().Y
			f.tid2 = ((f.ly1 * uint32(16)) + f.lx0)
			f.row3 = ((t.GroupID().Y * uint32(8)) + f.ly1)
			f.col4 = ((t.GroupID().X * uint32(16)) + f.lx0)
			f.acc5 = float32(0)
			f.zero6 = accel.ToFloat16(float32(0))
			f.pc = 1
			continue
		case 1:
			f.k07 = uint32(0)
			f.pc = 7
			continue
		case 2:
			if (f.row3 < d.M) && ((f.k07 + f.lx0) < d.K) {
				tr.Write(0, int(f.tid2))
				tileA[f.tid2] = a[(((f.row3 * d.K) + f.k07) + f.lx0)]
			} else {
				tr.Write(0, int(f.tid2))
				tileA[f.tid2] = f.zero6
			}
			f.kk8 = (f.tid2 / uint32(16))
			f.nn9 = (f.tid2 % uint32(16))
			if ((f.k07 + f.kk8) < d.K) && (((t.GroupID().X * uint32(16)) + f.nn9) < d.N) {
				tr.Write(1, int(f.tid2))
				tileB[f.tid2] = b[((((f.k07 + f.kk8) * d.N) + (t.GroupID().X * uint32(16))) + f.nn9)]
			} else {
				tr.Write(1, int(f.tid2))
				tileB[f.tid2] = f.zero6
			}
			f.kk210 = (f.kk8 + uint32(8))
			if ((f.k07 + f.kk210) < d.K) && (((t.GroupID().X * uint32(16)) + f.nn9) < d.N) {
				tr.Write(1, int((f.tid2 + uint32(128))))
				tileB[(f.tid2 + uint32(128))] = b[((((f.k07 + f.kk210) * d.N) + (t.GroupID().X * uint32(16))) + f.nn9)]
			} else {
				tr.Write(1, int((f.tid2 + uint32(128))))
				tileB[(f.tid2 + uint32(128))] = f.zero6
			}
			f.pc = 3
			continue
		case 3:
			f.pc = 4
			frame.Barrier = accel.KernelBarrierID{Index: 3, Pos: "gemm.go:86:3"}
			return true
		case 4:
			{
				f.k11 = uint32(0)
				for ; f.k11 < uint32(16); f.k11 = (f.k11 + uint32(1)) {
					f.av12 = tileA[tr.ReadAt(0, int(((f.ly1*uint32(16))+f.k11)))].F32()
					f.bv13 = tileB[tr.ReadAt(1, int(((f.k11*uint32(16))+f.lx0)))].F32()
					f.acc5 = float32(f.acc5 + float32(f.av12*f.bv13))
				}
			}
			f.pc = 5
			continue
		case 5:
			f.pc = 6
			frame.Barrier = accel.KernelBarrierID{Index: 5, Pos: "gemm.go:96:3"}
			return true
		case 6:
			f.k07 = (f.k07 + uint32(16))
			f.pc = 7
			continue
		case 7:
			if f.k07 < d.K {
				f.pc = 2
				continue
			}
			f.pc = 8
			continue
		case 8:
			if (f.row3 < d.M) && (f.col4 < d.N) {
				out[((f.row3 * d.N) + f.col4)] = f.acc5
			}
			return false
		}
		return false
	}
}

// MatMulTiledKernel is the compiled form of MatMulTiled.
var MatMulTiledKernel = accel.Kernel{
	Name:          "MatMulTiled",
	WorkgroupSize: accel.ID3{X: 16, Y: 8, Z: 1},
	Bindings: []accel.KernelBinding{
		{Name: "a", DType: accel.KernelF16, Access: accel.KernelRead},
		{Name: "b", DType: accel.KernelF16, Access: accel.KernelRead},
		{Name: "out", DType: accel.KernelF32, Access: accel.KernelWrite},
	},
	Digest:      "7d5374776e289634a322b661335b61b9",
	Generator:   accel.KernelABIVersion,
	Suspensions: 2,
	SharedSizes: []int{128, 256},
	NewShared: func() []any {
		var s0 [128]accel.Float16
		accel.KernelPoison(s0[:])
		var s1 [256]accel.Float16
		accel.KernelPoison(s1[:])
		return []any{&s0, &s1}
	},
	Uniforms: []accel.KernelUniform{
		{Name: "d", Type: "GEMMDims", Size: 16, Encode: func(dst []byte, v any) error {
			return accel.EncodeKernelUniform(dst, v, GEMMDimsCodec{}.Encode)
		}},
	},
	Cooperative: func(t accel.Thread, a accel.KernelArgs, slot *accel.KernelFrame) bool {
		f, _ := slot.State.(*matMulTiledFrame)
		if f == nil {
			f = &matMulTiledFrame{}
			slot.State = f
		}
		return matMulTiledCoop(t, accel.KernelUniformValue[GEMMDims](a, 0), accel.KernelSlice[accel.Float16](a, 0), accel.KernelSlice[accel.Float16](a, 1), accel.KernelSlice[float32](a, 2), accel.KernelShared[[128]accel.Float16](a, 0), accel.KernelShared[[256]accel.Float16](a, 1), f, slot, slot.Shared)
	},
}

// matVecFrame is one invocation's saved state between suspension points.
//
// Every local lives here rather than only those live across a barrier: that
// is a superset of the right answer and therefore correct, and a liveness
// analysis can shrink it later without changing anything a caller sees.
type matVecFrame struct {
	pc      int
	col0    uint32
	lid1    uint32
	acc2    float32
	k3      uint32
	stride4 uint32
}

// matVecCoop runs one invocation of MatVec to its next suspension point.
//
// It reports whether the invocation suspended. False means it finished, and
// the scheduler stops calling it. Each case is one state; the assignment to
// pc before continuing is the jump, which is explicit because a loop's states
// do not run in numeric order.
func matVecCoop(t accel.Thread, d GEMMDims, a []accel.Float16, b []accel.Float16, out []float32, sh *[128]float32, f *matVecFrame, frame *accel.KernelFrame, tr *accel.KernelSharedTracker) bool {
	for {
		switch f.pc {
		case 0:
			f.col0 = t.GroupID().X
			f.lid1 = t.LocalID().X
			f.acc2 = float32(0)
			if f.col0 < d.N {
				{
					f.k3 = f.lid1
					for ; f.k3 < d.K; f.k3 = (f.k3 + uint32(128)) {
						f.acc2 = float32(f.acc2 + float32(a[f.k3].F32()*b[((f.k3*d.N)+f.col0)].F32()))
					}
				}
			}
			tr.Write(0, int(f.lid1))
			sh[f.lid1] = f.acc2
			f.pc = 1
			continue
		case 1:
			f.pc = 2
			frame.Barrier = accel.KernelBarrierID{Index: 1, Pos: "matvec.go:38:2"}
			return true
		case 2:
			f.stride4 = uint32(64)
			f.pc = 6
			continue
		case 3:
			if f.lid1 < f.stride4 {
				tr.Write(0, int(f.lid1))
				sh[f.lid1] = float32(sh[tr.ReadAt(0, int(f.lid1))] + sh[tr.ReadAt(0, int((f.lid1+f.stride4)))])
			}
			f.pc = 4
			continue
		case 4:
			f.pc = 5
			frame.Barrier = accel.KernelBarrierID{Index: 4, Pos: "matvec.go:44:3"}
			return true
		case 5:
			f.stride4 = (f.stride4 / uint32(2))
			f.pc = 6
			continue
		case 6:
			if f.stride4 > uint32(0) {
				f.pc = 3
				continue
			}
			f.pc = 7
			continue
		case 7:
			if (f.lid1 == uint32(0)) && (f.col0 < d.N) {
				out[f.col0] = sh[tr.ReadAt(0, int(int32(0)))]
			}
			return false
		}
		return false
	}
}

// MatVecKernel is the compiled form of MatVec.
var MatVecKernel = accel.Kernel{
	Name:          "MatVec",
	WorkgroupSize: accel.ID3{X: 128, Y: 1, Z: 1},
	Bindings: []accel.KernelBinding{
		{Name: "a", DType: accel.KernelF16, Access: accel.KernelRead},
		{Name: "b", DType: accel.KernelF16, Access: accel.KernelRead},
		{Name: "out", DType: accel.KernelF32, Access: accel.KernelWrite},
	},
	Digest:      "40616d839a4fe81c847268e1029f0603",
	Generator:   accel.KernelABIVersion,
	Suspensions: 2,
	SharedSizes: []int{128},
	NewShared: func() []any {
		var s0 [128]float32
		accel.KernelPoison(s0[:])
		return []any{&s0}
	},
	Uniforms: []accel.KernelUniform{
		{Name: "d", Type: "GEMMDims", Size: 16, Encode: func(dst []byte, v any) error {
			return accel.EncodeKernelUniform(dst, v, GEMMDimsCodec{}.Encode)
		}},
	},
	Cooperative: func(t accel.Thread, a accel.KernelArgs, slot *accel.KernelFrame) bool {
		f, _ := slot.State.(*matVecFrame)
		if f == nil {
			f = &matVecFrame{}
			slot.State = f
		}
		return matVecCoop(t, accel.KernelUniformValue[GEMMDims](a, 0), accel.KernelSlice[accel.Float16](a, 0), accel.KernelSlice[accel.Float16](a, 1), accel.KernelSlice[float32](a, 2), accel.KernelShared[[128]float32](a, 0), f, slot, slot.Shared)
	},
}

// linearTiledFrame is one invocation's saved state between suspension points.
//
// Every local lives here rather than only those live across a barrier: that
// is a superset of the right answer and therefore correct, and a liveness
// analysis can shrink it later without changing anything a caller sees.
type linearTiledFrame struct {
	pc    int
	lx0   uint32
	ly1   uint32
	tid2  uint32
	row3  uint32
	col4  uint32
	acc5  float32
	zero6 accel.Float16
	k07   uint32
	kk8   uint32
	nn9   uint32
	kk210 uint32
	k11   uint32
	av12  float32
	bv13  float32
}

// linearTiledCoop runs one invocation of LinearTiled to its next suspension point.
//
// It reports whether the invocation suspended. False means it finished, and
// the scheduler stops calling it. Each case is one state; the assignment to
// pc before continuing is the jump, which is explicit because a loop's states
// do not run in numeric order.
func linearTiledCoop(t accel.Thread, d GEMMDims, a []accel.Float16, b []accel.Float16, bias []float32, out []float32, tileA *[128]accel.Float16, tileB *[256]accel.Float16, f *linearTiledFrame, frame *accel.KernelFrame, tr *accel.KernelSharedTracker) bool {
	for {
		switch f.pc {
		case 0:
			f.lx0 = t.LocalID().X
			f.ly1 = t.LocalID().Y
			f.tid2 = ((f.ly1 * uint32(16)) + f.lx0)
			f.row3 = ((t.GroupID().Y * uint32(8)) + f.ly1)
			f.col4 = ((t.GroupID().X * uint32(16)) + f.lx0)
			f.acc5 = float32(0)
			f.zero6 = accel.ToFloat16(float32(0))
			f.pc = 1
			continue
		case 1:
			f.k07 = uint32(0)
			f.pc = 7
			continue
		case 2:
			if (f.row3 < d.M) && ((f.k07 + f.lx0) < d.K) {
				tr.Write(0, int(f.tid2))
				tileA[f.tid2] = a[(((f.row3 * d.K) + f.k07) + f.lx0)]
			} else {
				tr.Write(0, int(f.tid2))
				tileA[f.tid2] = f.zero6
			}
			f.kk8 = (f.tid2 / uint32(16))
			f.nn9 = (f.tid2 % uint32(16))
			if ((f.k07 + f.kk8) < d.K) && (((t.GroupID().X * uint32(16)) + f.nn9) < d.N) {
				tr.Write(1, int(f.tid2))
				tileB[f.tid2] = b[((((f.k07 + f.kk8) * d.N) + (t.GroupID().X * uint32(16))) + f.nn9)]
			} else {
				tr.Write(1, int(f.tid2))
				tileB[f.tid2] = f.zero6
			}
			f.kk210 = (f.kk8 + uint32(8))
			if ((f.k07 + f.kk210) < d.K) && (((t.GroupID().X * uint32(16)) + f.nn9) < d.N) {
				tr.Write(1, int((f.tid2 + uint32(128))))
				tileB[(f.tid2 + uint32(128))] = b[((((f.k07 + f.kk210) * d.N) + (t.GroupID().X * uint32(16))) + f.nn9)]
			} else {
				tr.Write(1, int((f.tid2 + uint32(128))))
				tileB[(f.tid2 + uint32(128))] = f.zero6
			}
			f.pc = 3
			continue
		case 3:
			f.pc = 4
			frame.Barrier = accel.KernelBarrierID{Index: 3, Pos: "matvec.go:99:3"}
			return true
		case 4:
			{
				f.k11 = uint32(0)
				for ; f.k11 < uint32(16); f.k11 = (f.k11 + uint32(1)) {
					f.av12 = tileA[tr.ReadAt(0, int(((f.ly1*uint32(16))+f.k11)))].F32()
					f.bv13 = tileB[tr.ReadAt(1, int(((f.k11*uint32(16))+f.lx0)))].F32()
					f.acc5 = float32(f.acc5 + float32(f.av12*f.bv13))
				}
			}
			f.pc = 5
			continue
		case 5:
			f.pc = 6
			frame.Barrier = accel.KernelBarrierID{Index: 5, Pos: "matvec.go:107:3"}
			return true
		case 6:
			f.k07 = (f.k07 + uint32(16))
			f.pc = 7
			continue
		case 7:
			if f.k07 < d.K {
				f.pc = 2
				continue
			}
			f.pc = 8
			continue
		case 8:
			if (f.row3 < d.M) && (f.col4 < d.N) {
				out[((f.row3 * d.N) + f.col4)] = float32(f.acc5 + bias[f.col4])
			}
			return false
		}
		return false
	}
}

// LinearTiledKernel is the compiled form of LinearTiled.
var LinearTiledKernel = accel.Kernel{
	Name:          "LinearTiled",
	WorkgroupSize: accel.ID3{X: 16, Y: 8, Z: 1},
	Bindings: []accel.KernelBinding{
		{Name: "a", DType: accel.KernelF16, Access: accel.KernelRead},
		{Name: "b", DType: accel.KernelF16, Access: accel.KernelRead},
		{Name: "bias", DType: accel.KernelF32, Access: accel.KernelRead},
		{Name: "out", DType: accel.KernelF32, Access: accel.KernelWrite},
	},
	Digest:      "099087b7306af0d4bbc72ae7007e3ce7",
	Generator:   accel.KernelABIVersion,
	Suspensions: 2,
	SharedSizes: []int{128, 256},
	NewShared: func() []any {
		var s0 [128]accel.Float16
		accel.KernelPoison(s0[:])
		var s1 [256]accel.Float16
		accel.KernelPoison(s1[:])
		return []any{&s0, &s1}
	},
	Uniforms: []accel.KernelUniform{
		{Name: "d", Type: "GEMMDims", Size: 16, Encode: func(dst []byte, v any) error {
			return accel.EncodeKernelUniform(dst, v, GEMMDimsCodec{}.Encode)
		}},
	},
	Cooperative: func(t accel.Thread, a accel.KernelArgs, slot *accel.KernelFrame) bool {
		f, _ := slot.State.(*linearTiledFrame)
		if f == nil {
			f = &linearTiledFrame{}
			slot.State = f
		}
		return linearTiledCoop(t, accel.KernelUniformValue[GEMMDims](a, 0), accel.KernelSlice[accel.Float16](a, 0), accel.KernelSlice[accel.Float16](a, 1), accel.KernelSlice[float32](a, 2), accel.KernelSlice[float32](a, 3), accel.KernelShared[[128]accel.Float16](a, 0), accel.KernelShared[[256]accel.Float16](a, 1), f, slot, slot.Shared)
	},
}

// rMSNormFrame is one invocation's saved state between suspension points.
//
// Every local lives here rather than only those live across a barrier: that
// is a superset of the right answer and therefore correct, and a liveness
// analysis can shrink it later without changing anything a caller sees.
type rMSNormFrame struct {
	pc      int
	row0    uint32
	lid1    uint32
	base2   uint32
	acc3    float32
	i4      uint32
	v5      float32
	stride6 uint32
	mean7   float32
	scale8  float32
	i9      uint32
}

// rMSNormCoop runs one invocation of RMSNorm to its next suspension point.
//
// It reports whether the invocation suspended. False means it finished, and
// the scheduler stops calling it. Each case is one state; the assignment to
// pc before continuing is the jump, which is explicit because a loop's states
// do not run in numeric order.
func rMSNormCoop(t accel.Thread, d RowDims, x []float32, w []float32, out []float32, sh *[128]float32, f *rMSNormFrame, frame *accel.KernelFrame, tr *accel.KernelSharedTracker) bool {
	for {
		switch f.pc {
		case 0:
			f.row0 = t.GroupID().X
			f.lid1 = t.LocalID().X
			f.base2 = (f.row0 * d.Width)
			f.acc3 = float32(0)
			{
				f.i4 = f.lid1
				for ; f.i4 < d.Width; f.i4 = (f.i4 + uint32(128)) {
					f.v5 = x[(f.base2 + f.i4)]
					f.acc3 = float32(f.acc3 + float32(f.v5*f.v5))
				}
			}
			tr.Write(0, int(f.lid1))
			sh[f.lid1] = f.acc3
			f.pc = 1
			continue
		case 1:
			f.pc = 2
			frame.Barrier = accel.KernelBarrierID{Index: 1, Pos: "norm.go:60:2"}
			return true
		case 2:
			f.stride6 = uint32(64)
			f.pc = 6
			continue
		case 3:
			if f.lid1 < f.stride6 {
				tr.Write(0, int(f.lid1))
				sh[f.lid1] = float32(sh[tr.ReadAt(0, int(f.lid1))] + sh[tr.ReadAt(0, int((f.lid1+f.stride6)))])
			}
			f.pc = 4
			continue
		case 4:
			f.pc = 5
			frame.Barrier = accel.KernelBarrierID{Index: 4, Pos: "norm.go:66:3"}
			return true
		case 5:
			f.stride6 = (f.stride6 / uint32(2))
			f.pc = 6
			continue
		case 6:
			if f.stride6 > uint32(0) {
				f.pc = 3
				continue
			}
			f.pc = 7
			continue
		case 7:
			f.mean7 = (sh[tr.ReadAt(0, int(int32(0)))] / float32(d.Width))
			f.scale8 = kmath.RSqrt(float32(f.mean7 + d.Eps))
			{
				f.i9 = f.lid1
				for ; f.i9 < d.Width; f.i9 = (f.i9 + uint32(128)) {
					out[(f.base2 + f.i9)] = float32(float32(x[(f.base2+f.i9)]*f.scale8) * w[f.i9])
				}
			}
			return false
		}
		return false
	}
}

// RMSNormKernel is the compiled form of RMSNorm.
var RMSNormKernel = accel.Kernel{
	Name:          "RMSNorm",
	WorkgroupSize: accel.ID3{X: 128, Y: 1, Z: 1},
	Bindings: []accel.KernelBinding{
		{Name: "x", DType: accel.KernelF32, Access: accel.KernelRead},
		{Name: "w", DType: accel.KernelF32, Access: accel.KernelRead},
		{Name: "out", DType: accel.KernelF32, Access: accel.KernelWrite},
	},
	Digest:      "c7cd9d71d805420213e0a9705338effb",
	Generator:   accel.KernelABIVersion,
	Suspensions: 2,
	SharedSizes: []int{128},
	NewShared: func() []any {
		var s0 [128]float32
		accel.KernelPoison(s0[:])
		return []any{&s0}
	},
	Uniforms: []accel.KernelUniform{
		{Name: "d", Type: "RowDims", Size: 16, Encode: func(dst []byte, v any) error {
			return accel.EncodeKernelUniform(dst, v, RowDimsCodec{}.Encode)
		}},
	},
	Cooperative: func(t accel.Thread, a accel.KernelArgs, slot *accel.KernelFrame) bool {
		f, _ := slot.State.(*rMSNormFrame)
		if f == nil {
			f = &rMSNormFrame{}
			slot.State = f
		}
		return rMSNormCoop(t, accel.KernelUniformValue[RowDims](a, 0), accel.KernelSlice[float32](a, 0), accel.KernelSlice[float32](a, 1), accel.KernelSlice[float32](a, 2), accel.KernelShared[[128]float32](a, 0), f, slot, slot.Shared)
	},
}

// softmaxFrame is one invocation's saved state between suspension points.
//
// Every local lives here rather than only those live across a barrier: that
// is a superset of the right answer and therefore correct, and a liveness
// analysis can shrink it later without changing anything a caller sees.
type softmaxFrame struct {
	pc       int
	row0     uint32
	lid1     uint32
	base2    uint32
	m3       float32
	i4       uint32
	v5       float32
	stride6  uint32
	rowMax7  float32
	acc8     float32
	i9       uint32
	stride10 uint32
	total11  float32
	i12      uint32
}

// softmaxCoop runs one invocation of Softmax to its next suspension point.
//
// It reports whether the invocation suspended. False means it finished, and
// the scheduler stops calling it. Each case is one state; the assignment to
// pc before continuing is the jump, which is explicit because a loop's states
// do not run in numeric order.
func softmaxCoop(t accel.Thread, d RowDims, x []float32, out []float32, sh *[128]float32, f *softmaxFrame, frame *accel.KernelFrame, tr *accel.KernelSharedTracker) bool {
	for {
		switch f.pc {
		case 0:
			f.row0 = t.GroupID().X
			f.lid1 = t.LocalID().X
			f.base2 = (f.row0 * d.Width)
			f.m3 = x[(f.base2 + (f.lid1 % d.Width))]
			{
				f.i4 = f.lid1
				for ; f.i4 < d.Width; f.i4 = (f.i4 + uint32(128)) {
					f.v5 = x[(f.base2 + f.i4)]
					f.m3 = kmath.Max(f.m3, f.v5)
				}
			}
			tr.Write(0, int(f.lid1))
			sh[f.lid1] = f.m3
			f.pc = 1
			continue
		case 1:
			f.pc = 2
			frame.Barrier = accel.KernelBarrierID{Index: 1, Pos: "norm.go:109:2"}
			return true
		case 2:
			f.stride6 = uint32(64)
			f.pc = 6
			continue
		case 3:
			if f.lid1 < f.stride6 {
				tr.Write(0, int(f.lid1))
				sh[f.lid1] = kmath.Max(sh[tr.ReadAt(0, int(f.lid1))], sh[tr.ReadAt(0, int((f.lid1+f.stride6)))])
			}
			f.pc = 4
			continue
		case 4:
			f.pc = 5
			frame.Barrier = accel.KernelBarrierID{Index: 4, Pos: "norm.go:114:3"}
			return true
		case 5:
			f.stride6 = (f.stride6 / uint32(2))
			f.pc = 6
			continue
		case 6:
			if f.stride6 > uint32(0) {
				f.pc = 3
				continue
			}
			f.pc = 7
			continue
		case 7:
			f.rowMax7 = sh[tr.ReadAt(0, int(int32(0)))]
			f.pc = 8
			continue
		case 8:
			f.pc = 9
			frame.Barrier = accel.KernelBarrierID{Index: 8, Pos: "norm.go:117:2"}
			return true
		case 9:
			f.acc8 = float32(0)
			{
				f.i9 = f.lid1
				for ; f.i9 < d.Width; f.i9 = (f.i9 + uint32(128)) {
					f.acc8 = float32(f.acc8 + kmath.Exp(float32(x[(f.base2+f.i9)]-f.rowMax7)))
				}
			}
			tr.Write(0, int(f.lid1))
			sh[f.lid1] = f.acc8
			f.pc = 10
			continue
		case 10:
			f.pc = 11
			frame.Barrier = accel.KernelBarrierID{Index: 10, Pos: "norm.go:125:2"}
			return true
		case 11:
			f.stride10 = uint32(64)
			f.pc = 15
			continue
		case 12:
			if f.lid1 < f.stride10 {
				tr.Write(0, int(f.lid1))
				sh[f.lid1] = float32(sh[tr.ReadAt(0, int(f.lid1))] + sh[tr.ReadAt(0, int((f.lid1+f.stride10)))])
			}
			f.pc = 13
			continue
		case 13:
			f.pc = 14
			frame.Barrier = accel.KernelBarrierID{Index: 13, Pos: "norm.go:130:3"}
			return true
		case 14:
			f.stride10 = (f.stride10 / uint32(2))
			f.pc = 15
			continue
		case 15:
			if f.stride10 > uint32(0) {
				f.pc = 12
				continue
			}
			f.pc = 16
			continue
		case 16:
			f.total11 = sh[tr.ReadAt(0, int(int32(0)))]
			{
				f.i12 = f.lid1
				for ; f.i12 < d.Width; f.i12 = (f.i12 + uint32(128)) {
					out[(f.base2 + f.i12)] = float32(kmath.Exp(float32(x[(f.base2+f.i12)]-f.rowMax7)) / f.total11)
				}
			}
			return false
		}
		return false
	}
}

// SoftmaxKernel is the compiled form of Softmax.
var SoftmaxKernel = accel.Kernel{
	Name:          "Softmax",
	WorkgroupSize: accel.ID3{X: 128, Y: 1, Z: 1},
	Bindings: []accel.KernelBinding{
		{Name: "x", DType: accel.KernelF32, Access: accel.KernelRead},
		{Name: "out", DType: accel.KernelF32, Access: accel.KernelWrite},
	},
	Digest:      "e518f4545b053c2b559e4a27bfa8c48e",
	Generator:   accel.KernelABIVersion,
	Suspensions: 5,
	SharedSizes: []int{128},
	NewShared: func() []any {
		var s0 [128]float32
		accel.KernelPoison(s0[:])
		return []any{&s0}
	},
	Uniforms: []accel.KernelUniform{
		{Name: "d", Type: "RowDims", Size: 16, Encode: func(dst []byte, v any) error {
			return accel.EncodeKernelUniform(dst, v, RowDimsCodec{}.Encode)
		}},
	},
	Cooperative: func(t accel.Thread, a accel.KernelArgs, slot *accel.KernelFrame) bool {
		f, _ := slot.State.(*softmaxFrame)
		if f == nil {
			f = &softmaxFrame{}
			slot.State = f
		}
		return softmaxCoop(t, accel.KernelUniformValue[RowDims](a, 0), accel.KernelSlice[float32](a, 0), accel.KernelSlice[float32](a, 1), accel.KernelShared[[128]float32](a, 0), f, slot, slot.Shared)
	},
}

// segmentSumFlat is the generated flat lowering of SegmentSum.
//
// It is what the CPU backend runs. The authored SegmentSum is never registered as
// an executable: it supplies the typed source this was built from, and it is
// run only by the test that checks the two agree.
func segmentSumFlat(t accel.Thread, in []float32, out []float32) {
	var i uint32 = t.GlobalID().X
	var n uint32 = uint32(int32(len(out)))
	if i >= n {
		return
	}
	var width uint32 = uint32(4)
	var from uint32 = clampIndexFlat((i * width), uint32(int32(len(in))))
	var to uint32 = clampIndexFlat((from + width), uint32(int32(len(in))))
	out[i] = accumulateFlat(in, from, to)
}

// SegmentSumKernel is the compiled form of SegmentSum.
var SegmentSumKernel = accel.Kernel{
	Name:          "SegmentSum",
	WorkgroupSize: accel.ID3{X: 32, Y: 1, Z: 1},
	Bindings: []accel.KernelBinding{
		{Name: "in", DType: accel.KernelF32, Access: accel.KernelRead},
		{Name: "out", DType: accel.KernelF32, Access: accel.KernelWrite},
	},
	Digest:    "ece1409f99ec9848ed0055c27ca6268b",
	Generator: accel.KernelABIVersion,
	Flat: func(t accel.Thread, a accel.KernelArgs) {
		segmentSumFlat(t, accel.KernelSlice[float32](a, 0), accel.KernelSlice[float32](a, 1))
	},
}

// countAboveFlat is the generated flat lowering of CountAbove.
//
// It is what the CPU backend runs. The authored CountAbove is never registered as
// an executable: it supplies the typed source this was built from, and it is
// run only by the test that checks the two agree.
func countAboveFlat(t accel.Thread, in []float32, out []int32) {
	var i uint32 = t.GlobalID().X
	if i >= uint32(int32(len(out))) {
		return
	}
	var count int32 = int32(0)
	var limit uint32 = uint32(int32(len(in)))
	{
		var j uint32 = uint32(0)
		for ; j < limit; j = (j + uint32(1)) {
			if in[j] <= float32(0) {
				continue
			}
			count = (count + int32(1))
		}
	}
	var j uint32 = uint32(0)
	for j < limit {
		j = (j + uint32(1))
	}
	for {
		if j >= limit {
			break
		}
		j = (j + uint32(1))
	}
	out[i] = count
}

// CountAboveKernel is the compiled form of CountAbove.
var CountAboveKernel = accel.Kernel{
	Name:          "CountAbove",
	WorkgroupSize: accel.ID3{X: 16, Y: 1, Z: 1},
	Bindings: []accel.KernelBinding{
		{Name: "in", DType: accel.KernelF32, Access: accel.KernelRead},
		{Name: "out", DType: accel.KernelI32, Access: accel.KernelWrite},
	},
	Digest:    "d56dfd081a195284a7ad821f8d60d521",
	Generator: accel.KernelABIVersion,
	MSL: `#include <metal_stdlib>
using namespace metal;
#pragma METAL fp contract(off)

kernel void CountAbove(
    const device float *in [[buffer(0)]],
    device int *out [[buffer(1)]],
    constant uint *_lens [[buffer(2)]],
    uint3 _gid [[thread_position_in_grid]],
    uint3 _lid [[thread_position_in_threadgroup]],
    uint3 _wid [[threadgroup_position_in_grid]]) {
    uint i = _gid.x;
    if ((i >= uint(int(_lens[1])))) {
        return;
    }
    int count = int(0);
    uint limit = uint(int(_lens[0]));
    for (uint j = uint(0); (j < limit); j = (j + uint(1))) {
        if ((in[j] <= float(0))) {
            continue;
        }
        count = (count + int(1));
    }
    uint j = uint(0);
    for (; (j < limit); ) {
        j = (j + uint(1));
    }
    for (; ; ) {
        if ((j >= limit)) {
            break;
        }
        j = (j + uint(1));
    }
    out[i] = count;
}
`,
	Flat: func(t accel.Thread, a accel.KernelArgs) {
		countAboveFlat(t, accel.KernelSlice[float32](a, 0), accel.KernelSlice[int32](a, 1))
	},
}

// normalizeFlat is the generated flat lowering of Normalize.
//
// It is what the CPU backend runs. The authored Normalize is never registered as
// an executable: it supplies the typed source this was built from, and it is
// run only by the test that checks the two agree.
func normalizeFlat(t accel.Thread, in []accel.Float16, out []float32, scratch []float32) {
	var i uint32 = t.GlobalID().X
	if i >= uint32(int32(len(out))) {
		return
	}
	var x float32 = in[i].F32()
	var magnitude float32 = kmath.Sqrt(float32(kmath.Abs(x) + float32(1)))
	scratch[i] = magnitude
	out[i] = float32(x * kmath.RSqrt(float32(magnitude*magnitude)))
}

// NormalizeKernel is the compiled form of Normalize.
var NormalizeKernel = accel.Kernel{
	Name:          "Normalize",
	WorkgroupSize: accel.ID3{X: 32, Y: 1, Z: 1},
	Bindings: []accel.KernelBinding{
		{Name: "in", DType: accel.KernelF16, Access: accel.KernelRead},
		{Name: "out", DType: accel.KernelF32, Access: accel.KernelWrite},
		{Name: "scratch", DType: accel.KernelF32, Access: accel.KernelWrite},
	},
	Digest:    "7715f789607cc97e8f8efa2a27fa9302",
	Generator: accel.KernelABIVersion,
	Flat: func(t accel.Thread, a accel.KernelArgs) {
		normalizeFlat(t, accel.KernelSlice[accel.Float16](a, 0), accel.KernelSlice[float32](a, 1), accel.KernelSlice[float32](a, 2))
	},
}

// reduceSumFrame is one invocation's saved state between suspension points.
//
// Every local lives here rather than only those live across a barrier: that
// is a superset of the right answer and therefore correct, and a liveness
// analysis can shrink it later without changing anything a caller sees.
type reduceSumFrame struct {
	pc      int
	lid0    uint32
	n1      uint32
	acc2    float32
	i3      uint32
	stride4 uint32
}

// reduceSumCoop runs one invocation of ReduceSum to its next suspension point.
//
// It reports whether the invocation suspended. False means it finished, and
// the scheduler stops calling it. Each case is one state; the assignment to
// pc before continuing is the jump, which is explicit because a loop's states
// do not run in numeric order.
func reduceSumCoop(t accel.Thread, in []float32, out []float32, sh *[128]float32, f *reduceSumFrame, frame *accel.KernelFrame, tr *accel.KernelSharedTracker) bool {
	for {
		switch f.pc {
		case 0:
			f.lid0 = t.LocalID().X
			f.n1 = uint32(int32(len(in)))
			f.acc2 = float32(0)
			{
				f.i3 = f.lid0
				for ; f.i3 < f.n1; f.i3 = (f.i3 + uint32(128)) {
					f.acc2 = float32(f.acc2 + in[f.i3])
				}
			}
			tr.Write(0, int(f.lid0))
			sh[f.lid0] = f.acc2
			f.pc = 1
			continue
		case 1:
			f.pc = 2
			frame.Barrier = accel.KernelBarrierID{Index: 1, Pos: "reducesum.go:48:2"}
			return true
		case 2:
			f.stride4 = uint32(64)
			f.pc = 6
			continue
		case 3:
			if f.lid0 < f.stride4 {
				tr.Write(0, int(f.lid0))
				sh[f.lid0] = float32(sh[tr.ReadAt(0, int(f.lid0))] + sh[tr.ReadAt(0, int((f.lid0+f.stride4)))])
			}
			f.pc = 4
			continue
		case 4:
			f.pc = 5
			frame.Barrier = accel.KernelBarrierID{Index: 4, Pos: "reducesum.go:56:3"}
			return true
		case 5:
			f.stride4 = (f.stride4 / uint32(2))
			f.pc = 6
			continue
		case 6:
			if f.stride4 > uint32(0) {
				f.pc = 3
				continue
			}
			f.pc = 7
			continue
		case 7:
			if f.lid0 == uint32(0) {
				out[int32(0)] = sh[tr.ReadAt(0, int(int32(0)))]
			}
			return false
		}
		return false
	}
}

// ReduceSumKernel is the compiled form of ReduceSum.
var ReduceSumKernel = accel.Kernel{
	Name:          "ReduceSum",
	WorkgroupSize: accel.ID3{X: 128, Y: 1, Z: 1},
	Bindings: []accel.KernelBinding{
		{Name: "in", DType: accel.KernelF32, Access: accel.KernelRead},
		{Name: "out", DType: accel.KernelF32, Access: accel.KernelWrite},
	},
	Digest:      "9c1853e2164cfc8aec407d954cee51a5",
	Generator:   accel.KernelABIVersion,
	Suspensions: 2,
	SharedSizes: []int{128},
	NewShared: func() []any {
		var s0 [128]float32
		accel.KernelPoison(s0[:])
		return []any{&s0}
	},
	Cooperative: func(t accel.Thread, a accel.KernelArgs, slot *accel.KernelFrame) bool {
		f, _ := slot.State.(*reduceSumFrame)
		if f == nil {
			f = &reduceSumFrame{}
			slot.State = f
		}
		return reduceSumCoop(t, accel.KernelSlice[float32](a, 0), accel.KernelSlice[float32](a, 1), accel.KernelShared[[128]float32](a, 0), f, slot, slot.Shared)
	},
}

// scaleFlat is the generated flat lowering of Scale.
//
// It is what the CPU backend runs. The authored Scale is never registered as
// an executable: it supplies the typed source this was built from, and it is
// run only by the test that checks the two agree.
func scaleFlat(t accel.Thread, in []float32, out []float32) {
	var i uint32 = t.GlobalID().X
	if i < uint32(int32(len(out))) {
		out[i] = float32(in[i] * float32(2))
	}
}

// ScaleKernel is the compiled form of Scale.
var ScaleKernel = accel.Kernel{
	Name:          "Scale",
	WorkgroupSize: accel.ID3{X: 64, Y: 1, Z: 1},
	Bindings: []accel.KernelBinding{
		{Name: "in", DType: accel.KernelF32, Access: accel.KernelRead},
		{Name: "out", DType: accel.KernelF32, Access: accel.KernelWrite},
	},
	Digest:    "61408d149ab5bdfb1b1e24006bf2ea51",
	Generator: accel.KernelABIVersion,
	MSL: `#include <metal_stdlib>
using namespace metal;
#pragma METAL fp contract(off)

kernel void Scale(
    const device float *in [[buffer(0)]],
    device float *out [[buffer(1)]],
    constant uint *_lens [[buffer(2)]],
    uint3 _gid [[thread_position_in_grid]],
    uint3 _lid [[thread_position_in_threadgroup]],
    uint3 _wid [[threadgroup_position_in_grid]]) {
    uint i = _gid.x;
    if ((i < uint(int(_lens[1])))) {
        out[i] = (in[i] * float(2));
    }
}
`,
	Flat: func(t accel.Thread, a accel.KernelArgs) {
		scaleFlat(t, accel.KernelSlice[float32](a, 0), accel.KernelSlice[float32](a, 1))
	},
}

// transformFlat is the generated flat lowering of Transform.
//
// It is what the CPU backend runs. The authored Transform is never registered as
// an executable: it supplies the typed source this was built from, and it is
// run only by the test that checks the two agree.
func transformFlat(t accel.Thread, p Params, in []float32, out []float32) {
	var i uint32 = t.GlobalID().X
	if (i >= p.Steps) || (i >= uint32(int32(len(out)))) {
		return
	}
	var acc float32 = (float32(in[i]*p.Scale) + p.Origin[int32(0)])
	{
		var c uint32 = uint32(0)
		for ; c < uint32(4); c = (c + uint32(1)) {
			acc = float32(acc + float32(p.Inverse[c][int32(0)]*p.Origin[int32(1)]))
		}
	}
	out[i] = float32(acc + p.Origin[int32(2)])
}

// TransformKernel is the compiled form of Transform.
var TransformKernel = accel.Kernel{
	Name:          "Transform",
	WorkgroupSize: accel.ID3{X: 32, Y: 1, Z: 1},
	Bindings: []accel.KernelBinding{
		{Name: "in", DType: accel.KernelF32, Access: accel.KernelRead},
		{Name: "out", DType: accel.KernelF32, Access: accel.KernelWrite},
	},
	Digest:    "2aa00445fb65b63d0082756f22afbf1e",
	Generator: accel.KernelABIVersion,
	Uniforms: []accel.KernelUniform{
		{Name: "p", Type: "Params", Size: 96, Encode: func(dst []byte, v any) error {
			return accel.EncodeKernelUniform(dst, v, ParamsCodec{}.Encode)
		}},
	},
	Flat: func(t accel.Thread, a accel.KernelArgs) {
		transformFlat(t, accel.KernelUniformValue[Params](a, 0), accel.KernelSlice[float32](a, 0), accel.KernelSlice[float32](a, 1))
	},
}

// subgroupReduceFrame is one invocation's saved state between suspension points.
//
// Every local lives here rather than only those live across a barrier: that
// is a superset of the right answer and therefore correct, and a liveness
// analysis can shrink it later without changing anything a caller sees.
type subgroupReduceFrame struct {
	pc       int
	gid0     uint32
	v1       float32
	total2   float32
	elected3 bool
	sid4     uint32
}

// subgroupReduceCoop runs one invocation of SubgroupReduce to its next suspension point.
//
// It reports whether the invocation suspended. False means it finished, and
// the scheduler stops calling it. Each case is one state; the assignment to
// pc before continuing is the jump, which is explicit because a loop's states
// do not run in numeric order.
func subgroupReduceCoop(t accel.Thread, in []float32, out []float32, f *subgroupReduceFrame, frame *accel.KernelFrame, tr *accel.KernelSharedTracker) bool {
	for {
		switch f.pc {
		case 0:
			f.gid0 = t.GlobalID().X
			f.v1 = float32(0)
			if f.gid0 < uint32(int32(len(in))) {
				f.v1 = in[f.gid0]
			}
			f.pc = 1
			continue
		case 1:
			frame.Sub = accel.KernelSubAddF32
			frame.SubF32 = f.v1
			f.pc = 2
			frame.Barrier = accel.KernelBarrierID{Index: 1, Pos: "subgroup.go:31:2"}
			return true
		case 2:
			f.total2 = frame.SubF32
			f.pc = 3
			continue
		case 3:
			frame.Sub = accel.KernelSubElect
			f.pc = 4
			frame.Barrier = accel.KernelBarrierID{Index: 3, Pos: "subgroup.go:36:2"}
			return true
		case 4:
			f.elected3 = frame.SubBool
			f.pc = 5
			continue
		case 5:
			if f.elected3 {
				f.sid4 = t.SubgroupID()
				if f.sid4 < uint32(int32(len(out))) {
					out[f.sid4] = f.total2
				}
			}
			return false
		}
		return false
	}
}

// SubgroupReduceKernel is the compiled form of SubgroupReduce.
var SubgroupReduceKernel = accel.Kernel{
	Name:          "SubgroupReduce",
	WorkgroupSize: accel.ID3{X: 64, Y: 1, Z: 1},
	Bindings: []accel.KernelBinding{
		{Name: "in", DType: accel.KernelF32, Access: accel.KernelRead},
		{Name: "out", DType: accel.KernelF32, Access: accel.KernelWrite},
	},
	Digest:      "13a1a366d8c302729183a8dd065ee5dd",
	Generator:   accel.KernelABIVersion,
	Caps:        17,
	Suspensions: 2,
	Cooperative: func(t accel.Thread, a accel.KernelArgs, slot *accel.KernelFrame) bool {
		f, _ := slot.State.(*subgroupReduceFrame)
		if f == nil {
			f = &subgroupReduceFrame{}
			slot.State = f
		}
		return subgroupReduceCoop(t, accel.KernelSlice[float32](a, 0), accel.KernelSlice[float32](a, 1), f, slot, slot.Shared)
	},
}

// subgroupReduceFallbackFlat is the generated flat lowering of SubgroupReduceFallback.
//
// It is what the CPU backend runs. The authored SubgroupReduceFallback is never registered as
// an executable: it supplies the typed source this was built from, and it is
// run only by the test that checks the two agree.
func subgroupReduceFallbackFlat(t accel.Thread, in []float32, out []float32, width []uint32) {
	var lid uint32 = t.LocalID().X
	var gid uint32 = t.GlobalID().X
	var w uint32 = width[int32(0)]
	var sid uint32 = (lid / w)
	var lane uint32 = (lid % w)
	if lane == uint32(0) {
		var acc float32 = float32(0)
		{
			var l uint32 = uint32(0)
			for ; l < w; l = (l + uint32(1)) {
				var idx uint32 = ((gid - lane) + l)
				if idx < uint32(int32(len(in))) {
					acc = float32(acc + in[idx])
				}
			}
		}
		if sid < uint32(int32(len(out))) {
			out[sid] = acc
		}
	}
}

// SubgroupReduceFallbackKernel is the compiled form of SubgroupReduceFallback.
var SubgroupReduceFallbackKernel = accel.Kernel{
	Name:          "SubgroupReduceFallback",
	WorkgroupSize: accel.ID3{X: 64, Y: 1, Z: 1},
	Bindings: []accel.KernelBinding{
		{Name: "in", DType: accel.KernelF32, Access: accel.KernelRead},
		{Name: "out", DType: accel.KernelF32, Access: accel.KernelWrite},
		{Name: "width", DType: accel.KernelU32, Access: accel.KernelRead},
	},
	Digest:    "9f364410e5d670883ceafb06b3a0c60d",
	Generator: accel.KernelABIVersion,
	MSL: `#include <metal_stdlib>
using namespace metal;
#pragma METAL fp contract(off)

kernel void SubgroupReduceFallback(
    const device float *in [[buffer(0)]],
    device float *out [[buffer(1)]],
    const device uint *width [[buffer(2)]],
    constant uint *_lens [[buffer(3)]],
    uint3 _gid [[thread_position_in_grid]],
    uint3 _lid [[thread_position_in_threadgroup]],
    uint3 _wid [[threadgroup_position_in_grid]]) {
    uint lid = _lid.x;
    uint gid = _gid.x;
    uint w = width[int(0)];
    uint sid = (lid / w);
    uint lane = (lid % w);
    if ((lane == uint(0))) {
        float acc = float(0);
        for (uint l = uint(0); (l < w); l = (l + uint(1))) {
            uint idx = ((gid - lane) + l);
            if ((idx < uint(int(_lens[0])))) {
                acc = (acc + in[idx]);
            }
        }
        if ((sid < uint(int(_lens[1])))) {
            out[sid] = acc;
        }
    }
}
`,
	Flat: func(t accel.Thread, a accel.KernelArgs) {
		subgroupReduceFallbackFlat(t, accel.KernelSlice[float32](a, 0), accel.KernelSlice[float32](a, 1), accel.KernelSlice[uint32](a, 2))
	},
}

// Kernels is every kernel this package generated, in source order.
//
// Generated rather than written, so that a pass over the whole corpus cannot
// silently miss a kernel somebody added.
var Kernels = []*accel.Kernel{
	&AddKernel,
	&HistogramKernel,
	&AtomicOpsKernel,
	&CountWorkgroupsKernel,
	&AttentionDecodeKernel,
	&ExchangeKernel,
	&ReduceLoopKernel,
	&ReduceUnrolledKernel,
	&ElemAddKernel,
	&ElemMulKernel,
	&ElemScaleKernel,
	&SiLUKernel,
	&SwiGLUKernel,
	&GatherRowsKernel,
	&ScatterRowsKernel,
	&RoPEKernel,
	&MatMulTiledKernel,
	&MatVecKernel,
	&LinearTiledKernel,
	&RMSNormKernel,
	&SoftmaxKernel,
	&SegmentSumKernel,
	&CountAboveKernel,
	&NormalizeKernel,
	&ReduceSumKernel,
	&ScaleKernel,
	&TransformKernel,
	&SubgroupReduceKernel,
	&SubgroupReduceFallbackKernel,
}
