// Copyright 2026 The golang.design Initiative Authors.
// All rights reserved. Use of this source code is governed by
// a BSD-style license that can be found in the LICENSE file.

// Package emit turns the typed IR into the generated Go lowering.
//
// # The authored function is not the executable
//
// This is spec 000 decision 5, and it is the reason the whole compiler exists
// in this shape. The CPU backend does not call the function a kernel author
// wrote. It calls this, generated from the same IR every GPU artifact is
// generated from, with an explicit operation at every load, store, and
// arithmetic rounding point.
//
// The cost is a whole class of bug: a mistake in IR construction produces a CPU
// runner and a GPU artifact that agree with each other and disagree with the Go
// program the author read. Differential execution cannot see that, because it is
// wrong identically everywhere. So the authored function is still run, by the
// test at spec 004's fifth level, against this.
//
// The gain is that the CPU backend becomes an oracle rather than a second
// implementation. Two implementations of the same maths disagree in ways nobody
// can attribute; one IR lowered twice disagrees only where the hardware does.
//
// # Why the rounding points are explicit
//
// float32(a * b) rather than a * b. Go permits a compiler to keep an
// intermediate wider than float32, and on a host with FMA it will, so the
// authored function and this one can differ in the last bit. Writing the
// rounding down makes the generated lowering say exactly what the GPU does,
// which is what lets spec 008 bound the difference instead of hoping there
// isn't one.
package emit

import (
	"bytes"
	"fmt"
	"go/format"
	"strings"

	"golang.design/x/accel/internal/kernelc/ir"
)

// Package describes what to generate.
type Package struct {
	// Name is the Go package clause the generated file carries.
	Name string

	// Kernels are the kernels found in it, in source order.
	Kernels []*ir.Func
}

// Generate produces the generated file's contents, gofmt'd.
func Generate(p Package) ([]byte, error) {
	var b bytes.Buffer

	fmt.Fprintf(&b, "// Code generated by accel-kernel. DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", p.Name)
	fmt.Fprintf(&b, "import %q\n\n", "golang.design/x/accel")

	e := &emitter{buf: &b}

	// Helpers first, and each one once however many kernels reach it. Every
	// target that requires declaration before use gets it for free, and the Go
	// lowering does not care but reads the same way as the others.
	seen := map[*ir.Func]bool{}
	for _, k := range p.Kernels {
		for _, h := range k.Helpers {
			if !seen[h] {
				seen[h] = true
				e.helper(h)
			}
		}
	}
	for _, k := range p.Kernels {
		e.kernel(k)
	}
	if e.err != nil {
		return nil, e.err
	}

	// Formatting the result rather than emitting formatted text is deliberate:
	// a generated file that is not gofmt'd fails the repository's own gate, and
	// keeping the emitter's output pretty by hand is work that buys nothing.
	out, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("accel: the generated source for package %s does not parse: %w\n%s",
			p.Name, err, b.String())
	}
	return out, nil
}

type emitter struct {
	buf *bytes.Buffer
	err error
}

func (e *emitter) fail(format string, args ...any) {
	if e.err == nil {
		e.err = fmt.Errorf("accel: "+format, args...)
	}
}

func (e *emitter) printf(format string, args ...any) {
	if e.err == nil {
		fmt.Fprintf(e.buf, format, args...)
	}
}

// kernel emits one kernel's lowering, record, and entry point.
func (e *emitter) kernel(k *ir.Func) {
	lower := lowerName(k.Name)

	e.printf("// %s is the generated flat lowering of %s.\n", lower, k.Name)
	e.printf("//\n")
	e.printf("// It is what the CPU backend runs. The authored %s is never registered as\n", k.Name)
	e.printf("// an executable: it supplies the typed source this was built from, and it is\n")
	e.printf("// run only by the test that checks the two agree.\n")
	e.printf("func %s(", lower)
	for i, p := range k.Params {
		if i > 0 {
			e.printf(", ")
		}
		e.printf("%s %s", p.Name, e.goType(p.Type()))
	}
	e.printf(") {\n")
	e.block(k.Body, 1)
	e.printf("}\n\n")

	e.printf("// %s is the compiled form of %s.\n", k.Name+"Kernel", k.Name)
	e.printf("var %s = accel.Kernel{\n", k.Name+"Kernel")
	e.printf("\tName: %q,\n", k.Name)
	e.printf("\tWorkgroupSize: accel.ID3{X: %d, Y: %d, Z: %d},\n",
		k.Workgroup[0], k.Workgroup[1], k.Workgroup[2])
	e.printf("\tBindings: []accel.KernelBinding{\n")
	for _, b := range k.Bindings {
		e.printf("\t\t{Name: %q, DType: %s, Access: %s},\n", b.Name, e.dtype(b.Type), access(b))
	}
	e.printf("\t},\n")
	e.printf("\tDigest: %q,\n", k.Digest)
	e.printf("\tGenerator: accel.KernelABIVersion,\n")
	e.printf("\tFlat: func(t accel.Thread, a accel.KernelArgs) {\n")
	e.printf("\t\t%s(t", lower)
	for i, b := range k.Bindings {
		e.printf(", accel.KernelSlice[%s](a, %d)", e.goType(b.Type.Elem), i)
	}
	e.printf(")\n")
	e.printf("\t},\n")
	e.printf("}\n\n")
}

// helper emits one helper's lowering.
func (e *emitter) helper(h *ir.Func) {
	name := lowerName(h.Name)
	e.printf("// %s is the generated lowering of the helper %s.\n", name, h.Name)
	e.printf("func %s(", name)
	for i, p := range h.Params {
		if i > 0 {
			e.printf(", ")
		}
		e.printf("%s %s", p.Name, e.goType(p.Type()))
	}
	e.printf(")")
	if h.Result != nil {
		e.printf(" %s", e.goType(h.Result))
	}
	e.printf(" {\n")
	e.block(h.Body, 1)
	e.printf("}\n\n")
}

// lowerName is the unexported name a kernel's lowering takes.
func lowerName(name string) string {
	if name == "" {
		return "flat"
	}
	return strings.ToLower(name[:1]) + name[1:] + "Flat"
}

func access(b *ir.Binding) string {
	switch {
	case b.Read && b.Write:
		return "accel.KernelRead | accel.KernelWrite"
	case b.Write:
		return "accel.KernelWrite"
	default:
		return "accel.KernelRead"
	}
}

// block emits a statement list at the given indent.
func (e *emitter) block(b *ir.Block, depth int) {
	for _, s := range b.List {
		e.stmt(s, depth)
	}
}

func indent(depth int) string { return strings.Repeat("\t", depth) }

// stmt emits one statement.
func (e *emitter) stmt(s ir.Stmt, depth int) {
	switch s := s.(type) {
	case *ir.Block:
		e.printf("%s{\n", indent(depth))
		e.block(s, depth+1)
		e.printf("%s}\n", indent(depth))

	case *ir.Declare:
		e.printf("%svar %s %s = ", indent(depth), s.Local.Name, e.goType(s.Local.Type()))
		e.value(s.Init)
		e.printf("\n")

	case *ir.Assign:
		e.printf("%s", indent(depth))
		e.value(s.LHS)
		e.printf(" = ")
		e.rounded(s.RHS)
		e.printf("\n")

	case *ir.ExprStmt:
		e.printf("%s", indent(depth))
		e.value(s.X)
		e.printf("\n")

	case *ir.If:
		e.printf("%sif ", indent(depth))
		e.value(s.Cond)
		e.printf(" {\n")
		e.block(s.Then, depth+1)
		if s.Else == nil {
			e.printf("%s}\n", indent(depth))
			return
		}
		e.printf("%s} else ", indent(depth))
		switch els := s.Else.(type) {
		case *ir.Block:
			e.printf("{\n")
			e.block(els, depth+1)
			e.printf("%s}\n", indent(depth))
		default:
			e.printf("\n")
			e.stmt(s.Else, depth)
		}

	case *ir.For:
		e.forStmt(s, depth)

	case *ir.Break:
		e.printf("%sbreak\n", indent(depth))

	case *ir.Continue:
		e.printf("%scontinue\n", indent(depth))

	case *ir.Return:
		if s.Value == nil {
			e.printf("%sreturn\n", indent(depth))
			return
		}
		e.printf("%sreturn ", indent(depth))
		e.rounded(s.Value)
		e.printf("\n")

	default:
		e.fail("no lowering for statement %T", s)
	}
}

// forStmt emits a loop.
//
// A loop whose init declares a variable is wrapped in a block, and the
// declaration is hoisted out of the clause. Go's for-init takes a simple
// statement and `var x T = v` is not one, so the alternative is emitting
// `x := v` in the clause. That would work and it would throw away a check worth
// keeping: `var x T = v` is a compile error when the IR says a local has one
// type and its initializer another, and `:=` silently takes whatever the
// initializer happened to be. The wrapping block keeps the scope exactly as
// narrow as the loop's, so nothing else changes.
func (e *emitter) forStmt(s *ir.For, depth int) {
	body := depth
	if decl, ok := s.Init.(*ir.Declare); ok {
		e.printf("%s{\n", indent(depth))
		body = depth + 1
		e.stmt(decl, body)
	}

	e.printf("%sfor ", indent(body))
	switch {
	case s.Init != nil || s.Post != nil:
		e.printf("; ")
		if s.Cond != nil {
			e.value(s.Cond)
		}
		e.printf("; ")
		e.inline(s.Post)
	case s.Cond != nil:
		e.value(s.Cond)
	}
	e.printf(" {\n")
	e.block(s.Body, body+1)
	e.printf("%s}\n", indent(body))

	if body != depth {
		e.printf("%s}\n", indent(depth))
	}
}

// inline emits a statement in the single-line form a for clause takes, which is
// a simple statement and never a declaration.
func (e *emitter) inline(s ir.Stmt) {
	switch s := s.(type) {
	case nil:
	case *ir.Assign:
		e.value(s.LHS)
		e.printf(" = ")
		e.rounded(s.RHS)
	default:
		e.fail("no lowering for %T in a for clause: it takes a simple statement", s)
	}
}

// rounded emits a value with the explicit rounding point its type requires.
//
// This is the whole point of generating rather than calling. Go permits an
// intermediate float32 expression to be evaluated wider, and on a host with FMA
// it is, so a * b + c can differ from the GPU in the last bit. Naming the
// rounding makes the lowering say what the GPU does. Integer arithmetic has no
// such freedom and is left alone, because a redundant conversion there is noise
// in every generated file.
func (e *emitter) rounded(v ir.Value) {
	if !needsRounding(v) {
		e.value(v)
		return
	}
	// A binary operation already parenthesizes itself, so naming the conversion
	// in front of it is enough. Wrapping again would double the parentheses in
	// every arithmetic expression in every generated file, which is noise a
	// reader has to see past to check the lowering.
	if _, isBinary := v.(*ir.Binary); isBinary {
		e.printf("float32")
		e.value(v)
		return
	}
	e.printf("float32(")
	e.value(v)
	e.printf(")")
}

// needsRounding reports whether a value is f32 arithmetic whose intermediate a
// compiler may keep wider.
func needsRounding(v ir.Value) bool {
	if v.Type() == nil || v.Type().Kind != ir.F32 {
		return false
	}
	switch v.(type) {
	case *ir.Binary, *ir.Unary:
		return true
	}
	return false
}

// value emits an expression.
func (e *emitter) value(v ir.Value) {
	switch v := v.(type) {
	case *ir.Const:
		e.constant(v)

	case *ir.Param:
		e.printf("%s", v.Name)

	case *ir.Local:
		e.printf("%s", v.Name)

	case *ir.FieldSel:
		e.value(v.X)
		e.printf(".%s", v.Name)

	case *ir.IndexExpr:
		e.value(v.X)
		e.printf("[")
		e.value(v.Index)
		e.printf("]")

	case *ir.Unary:
		e.printf("%s", v.Op)
		e.value(v.X)

	case *ir.Binary:
		e.printf("(")
		e.rounded(v.X)
		e.printf(" %s ", v.Op)
		e.rounded(v.Y)
		e.printf(")")

	case *ir.Convert:
		e.printf("%s(", e.goType(v.Type()))
		e.value(v.X)
		e.printf(")")

	case *ir.Len:
		e.printf("int32(len(")
		e.value(v.X)
		e.printf("))")

	case *ir.IntrinsicCall:
		e.intrinsic(v)

	case *ir.Call:
		e.printf("%s(", lowerName(v.Callee.Name))
		for i, a := range v.Args {
			if i > 0 {
				e.printf(", ")
			}
			e.value(a)
		}
		e.printf(")")

	default:
		e.fail("no lowering for value %T", v)
	}
}

// constant emits a literal in its resolved type.
//
// In its resolved type, which is where the GLSL integer-literal divergence is
// settled at the root: the emitter knows whether the 2 in gid*2 is u32 or f32
// and spells it accordingly, rather than coercing an id to int to keep the
// literal legal.
func (e *emitter) constant(c *ir.Const) {
	if c.Val == nil {
		e.fail("a constant with no value at %v", c.Pos())
		return
	}
	switch c.Type().Kind {
	case ir.Bool:
		e.printf("%s", c.Val.String())
	case ir.F32:
		e.printf("float32(%s)", c.Val.ExactString())
	default:
		e.printf("%s(%s)", e.goType(c.Type()), c.Val.String())
	}
}

// intrinsic emits a thread-id accessor.
func (e *emitter) intrinsic(v *ir.IntrinsicCall) {
	name, ok := intrinsicMethod[v.Op]
	if !ok {
		e.fail("no lowering for intrinsic %v at %v", v.Op, v.Pos())
		return
	}
	if v.Recv == nil {
		e.fail("intrinsic %v has no receiver at %v", v.Op, v.Pos())
		return
	}
	e.value(v.Recv)
	e.printf(".%s(", name)
	for i, a := range v.Args {
		if i > 0 {
			e.printf(", ")
		}
		e.value(a)
	}
	e.printf(")")
}

// intrinsicMethod maps an opcode back to the method the runtime provides.
//
// The generated code calls accel.Thread's own accessors rather than reaching
// into the ids directly, because the ids are the backend's to own: at M4 a
// Thread carries rendezvous state, and a lowering that had copied the ids out
// would be holding a stale half of it.
var intrinsicMethod = map[ir.Opcode]string{
	ir.OpGlobalID:    "GlobalID",
	ir.OpLocalID:     "LocalID",
	ir.OpGroupID:     "GroupID",
	ir.OpGlobalIndex: "GlobalIndex",
	ir.OpLocalIndex:  "LocalIndex",
	ir.OpGroupIndex:  "GroupIndex",
}

// goType is the Go spelling of an IR type.
func (e *emitter) goType(t *ir.Type) string {
	if t == nil {
		e.fail("a value with no type")
		return "invalid"
	}
	switch t.Kind {
	case ir.Bool:
		return "bool"
	case ir.I32:
		return "int32"
	case ir.U32:
		return "uint32"
	case ir.F32:
		return "float32"
	case ir.I8:
		return "int8"
	case ir.U8:
		return "uint8"
	case ir.F16, ir.BF16:
		// A 16-bit float is stored, never computed. Go has no float16, and the
		// subset has no arithmetic on one, so the host slice a narrow binding
		// binds to is []uint16 and the conversion to f32 is explicit in the
		// kernel's own source.
		return "uint16"
	case ir.ID3Kind:
		return "accel.ID3"
	case ir.Struct:
		if t.Name == "Thread" {
			return "accel.Thread"
		}
		return t.Name
	case ir.Slice:
		return "[]" + e.goType(t.Elem)
	case ir.Array:
		return fmt.Sprintf("[%d]%s", t.Len, e.goType(t.Elem))
	}
	e.fail("no Go spelling for type %v", t)
	return "invalid"
}

// dtype is the generated spelling of a binding's element type.
func (e *emitter) dtype(t *ir.Type) string {
	if t == nil || t.Elem == nil {
		e.fail("a binding with no element type")
		return "accel.KernelF32"
	}
	switch t.Elem.Kind {
	case ir.F32:
		return "accel.KernelF32"
	case ir.I32:
		return "accel.KernelI32"
	case ir.U32:
		return "accel.KernelU32"
	case ir.I8:
		return "accel.KernelI8"
	case ir.U8:
		return "accel.KernelU8"
	case ir.F16:
		return "accel.KernelF16"
	case ir.BF16:
		return "accel.KernelBF16"
	}
	e.fail("no dtype for binding element %v", t.Elem)
	return "accel.KernelF32"
}
