// Copyright 2026 The golang.design Initiative Authors.
// All rights reserved. Use of this source code is governed by
// a BSD-style license that can be found in the LICENSE file.

package emit_test

import (
	"flag"
	"go/ast"
	"go/parser"
	"go/token"
	"go/types"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"testing"

	"golang.design/x/accel/internal/kernelc/emit"
	"golang.design/x/accel/internal/kernelc/front"
	"golang.design/x/accel/internal/kernelc/ir"
	"golang.org/x/tools/go/packages"
)

var update = flag.Bool("update", false, "rewrite the golden files")

// normalizeEOL makes a comparison about text rather than about line endings.
func normalizeEOL(s string) string { return strings.ReplaceAll(s, "\r\n", "\n") }

// TestGoldenOutput is spec 004's first testing level: emitted text is
// byte-stable for a fixed input.
//
// The predecessor's equivalent, asserting that existing kernels emit
// byte-identically after a compiler change, caught real regressions and is
// carried forward. A golden is weak evidence about whether the output is right
// and strong evidence about whether it changed, which is the question a
// reviewer of a compiler change actually has.
func TestGoldenOutput(t *testing.T) {
	out := generateCorpus(t)
	golden := filepath.Join("testdata", "testkernels.golden")

	if *update {
		if err := os.MkdirAll("testdata", 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(golden, out, 0o644); err != nil {
			t.Fatal(err)
		}
		t.Log("golden rewritten")
		return
	}

	want, err := os.ReadFile(golden)
	if err != nil {
		t.Fatalf("%v\nrun: go test ./internal/kernelc/emit -update", err)
	}
	// Line endings are normalized before comparing. The golden is checked in
	// with LF and .gitattributes keeps it that way, but a checkout configured
	// otherwise would rewrite it and produce a failure whose diff shows nothing,
	// which is a worse way to learn about a git setting than a one-line
	// normalization.
	if normalizeEOL(string(out)) != normalizeEOL(string(want)) {
		t.Errorf("generated output changed. If the change is intended, rerun with -update "+
			"and review the diff.\n--- got ---\n%s\n--- want ---\n%s", out, want)
	}
}

// TestGeneratedSourceTypeChecks is the level above a golden. Golden text that
// does not compile is worthless, and the emitter is the only thing standing
// between the IR and a package that has to build.
func TestGeneratedSourceTypeChecks(t *testing.T) {
	out := generateCorpus(t)

	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, "generated.go", out, parser.ParseComments)
	if err != nil {
		t.Fatalf("the generated source does not parse: %v\n%s", err, out)
	}

	// The authored source is type-checked alongside it, because the two share a
	// package and the generated lowering names types the authored file imports.
	authored, err := os.ReadFile(filepath.Join("..", "..", "testkernels", "scale.go"))
	if err != nil {
		t.Fatal(err)
	}
	af, err := parser.ParseFile(fset, "scale.go", authored, parser.ParseComments)
	if err != nil {
		t.Fatal(err)
	}

	conf := types.Config{Importer: importerFor(t)}
	if _, err := conf.Check("golang.design/x/accel/internal/testkernels", fset,
		[]*ast.File{af, f}, nil); err != nil {
		t.Fatalf("the generated source does not type-check: %v\n%s", err, out)
	}
}

// TestGeneratedShape checks the parts a reader would otherwise have to diff a
// golden to see.
func TestGeneratedShape(t *testing.T) {
	out := string(generateCorpus(t))

	for _, want := range []string{
		"// Code generated by accel-kernel. DO NOT EDIT.",
		"package testkernels",
		"func scaleFlat(t accel.Thread, in []float32, out []float32)",
		"var ScaleKernel = accel.Kernel{",
		`Name:          "Scale"`,
		"WorkgroupSize: accel.ID3{X: 64, Y: 1, Z: 1}",
		`{Name: "in", DType: accel.KernelF32, Access: accel.KernelRead}`,
		`{Name: "out", DType: accel.KernelF32, Access: accel.KernelWrite}`,
		"Generator: accel.KernelABIVersion",
		"accel.KernelSlice[float32](a, 0)",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("the generated file does not contain %q:\n%s", want, out)
		}
	}

	// The rounding point is the reason this is generated rather than called.
	if !strings.Contains(out, "float32(in[i] * float32(2))") {
		t.Errorf("the multiplication has no explicit rounding point: Go may keep an f32 "+
			"intermediate wider, so a lowering without one does not say what the GPU does\n%s", out)
	}

	// It imports only the public package. Generated code lives in a caller's
	// package, and an internal path is importable by this module alone.
	if strings.Contains(out, "internal/kernel") {
		t.Errorf("the generated file names an internal package, so it would compile only "+
			"inside this module:\n%s", out)
	}
}

// TestDigestCoversMoreThanSource is the property that makes freshness mean
// anything: an input that changes what the generated file should contain must
// change the digest, even when the authored source is untouched.
func TestDigestCoversMoreThanSource(t *testing.T) {
	base := loadCorpus(t)[0]
	baseline := emit.Digest(base)

	if emit.Digest(base) != baseline {
		t.Fatal("the digest is not stable across calls")
	}

	for _, tc := range []struct {
		name   string
		mutate func(k *ir.Func)
	}{
		{"source", func(k *ir.Func) { k.Source += " " }},
		{"name", func(k *ir.Func) { k.Name = "Other" }},
		{"workgroup extent", func(k *ir.Func) { k.Workgroup[0] = 128 }},
		{"binding name", func(k *ir.Func) { k.Bindings[0].Name = "renamed" }},
		{"binding access", func(k *ir.Func) { k.Bindings[0].Write = true }},
		{"binding element type", func(k *ir.Func) { k.Bindings[0].Type.Elem = &ir.Type{Kind: ir.I32} }},
		{"intrinsic set", func(k *ir.Func) { k.Intrinsics = append(k.Intrinsics, "accel.Thread.LocalID") }},
		{"thread position", func(k *ir.Func) { k.Thread = 1 }},
	} {
		t.Run(tc.name, func(t *testing.T) {
			k := loadCorpus(t)[0]
			tc.mutate(k)
			if got := emit.Digest(k); got == baseline {
				t.Errorf("changing the %s left the digest unchanged, so a generated file "+
					"built before the change would still report itself fresh", tc.name)
			}
		})
	}
}

// TestPreimageExplainsAMismatch checks that a freshness failure can say which
// input moved. "The digest differs" leaves a reader guessing between half a
// dozen possibilities.
func TestPreimageExplainsAMismatch(t *testing.T) {
	k := loadCorpus(t)[0]
	p := emit.Preimage(k)

	for _, want := range []string{
		"generator/", "abi/kernel/", "abi/intrin/",
		"kernel\tScale", "workgroup\t64\t1\t1",
		"binding\t1\tin\t[]f32\tread", "binding\t2\tout\t[]f32\twrite",
		"intrinsic\taccel.Thread.GlobalID",
		"helpers\t0",
		"source\t",
	} {
		if !strings.Contains(p, want) {
			t.Errorf("the preimage does not carry %q:\n%s", want, p)
		}
	}

	// The version lines come first, so a diff of two preimages shows the
	// cheapest explanation at the top.
	lines := strings.SplitN(p, "\n", 4)
	if !strings.HasPrefix(lines[0], "generator/") {
		t.Errorf("the preimage starts with %q, want the generator version", lines[0])
	}

	// The helpers section exists and is empty, so spec 013 adds lines rather
	// than changing the format and reissuing every committed generated file.
	if !strings.Contains(p, "helpers\t0\n") {
		t.Error("the preimage has no helpers section, so adding helpers would change its format")
	}
}

// TestEmitterRejectsWhatItCannotLower checks that a node with no lowering is an
// error rather than silently missing output. A generator that drops a statement
// produces a kernel that compiles and computes something else.
func TestEmitterRejectsWhatItCannotLower(t *testing.T) {
	p := token.Pos(1)
	f32 := &ir.Type{Kind: ir.F32}

	for _, tc := range []struct {
		name string
		k    *ir.Func
		want string
	}{
		{
			name: "unknown intrinsic",
			k: kernelWith(ir.NewExprStmt(p,
				ir.NewIntrinsic(p, f32, ir.OpBarrier, ir.NewParam(p, f32, 0, "t", nil), nil))),
			want: "no lowering for intrinsic",
		},
		{
			name: "intrinsic with no receiver",
			k:    kernelWith(ir.NewExprStmt(p, ir.NewIntrinsic(p, f32, ir.OpGlobalID, nil, nil))),
			want: "has no receiver",
		},
		{
			name: "constant with no value",
			k:    kernelWith(ir.NewExprStmt(p, ir.NewConst(p, f32, nil))),
			want: "constant with no value",
		},
		{
			name: "type with no Go spelling",
			k:    kernelWith(ir.NewExprStmt(p, ir.NewConst(p, &ir.Type{Kind: ir.Kind(99)}, nil))),
			want: "constant with no value",
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			_, err := emit.Generate(emit.Package{Name: "p", Kernels: []*ir.Func{tc.k}})
			if err == nil {
				t.Fatal("was emitted")
			}
			if !strings.Contains(err.Error(), tc.want) {
				t.Errorf("error %q does not carry %q", err, tc.want)
			}
		})
	}
}

// kernelWith wraps one statement in an otherwise valid kernel.
func kernelWith(s ir.Stmt) *ir.Func {
	p := token.Pos(1)
	f32s := &ir.Type{Kind: ir.Slice, Elem: &ir.Type{Kind: ir.F32}}
	return &ir.Func{
		Name: "K", Kernel: true, Workgroup: [3]uint32{64, 1, 1}, Thread: 0,
		Params: []*ir.Param{
			ir.NewParam(p, &ir.Type{Kind: ir.Struct, Name: "Thread"}, 0, "t", nil),
			ir.NewParam(p, f32s, 1, "out", nil),
		},
		Bindings: []*ir.Binding{{Name: "out", Index: 1, Type: f32s, Write: true}},
		Body:     ir.NewBlock(p, s),
	}
}

// generateCorpus builds the generated file for the corpus package.
func generateCorpus(t testing.TB) []byte {
	t.Helper()
	kernels := loadCorpus(t)
	for _, k := range kernels {
		k.Digest = emit.Digest(k)
	}
	out, err := emit.Generate(emit.Package{Name: "testkernels", Kernels: kernels})
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	return out
}

// loadCorpus type-checks and builds the corpus kernels, freshly each call so a
// mutation in one test cannot reach another.
func loadCorpus(t testing.TB) []*ir.Func {
	t.Helper()
	pkgs, err := front.Load(filepath.Join("..", "..", ".."), "golang.design/x/accel/internal/testkernels")
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	kernels, diags := front.Check(pkgs[0])
	if len(diags) > 0 {
		t.Fatalf("the corpus was rejected:\n%v", diags)
	}
	if len(kernels) == 0 {
		t.Fatal("the corpus has no kernels")
	}
	return kernels
}

var (
	importerOnce sync.Once
	importerVal  types.Importer
)

// importerFor serves the one import a generated kernel file has.
func importerFor(t testing.TB) types.Importer {
	t.Helper()
	importerOnce.Do(func() {
		cfg := &packages.Config{Mode: packages.NeedName | packages.NeedTypes | packages.NeedDeps | packages.NeedImports}
		pkgs, err := packages.Load(cfg, "golang.design/x/accel")
		if err != nil {
			t.Fatalf("loading accel: %v", err)
		}
		byPath := map[string]*types.Package{}
		for _, p := range pkgs {
			byPath[p.PkgPath] = p.Types
		}
		importerVal = mapImporter(byPath)
	})
	return importerVal
}

type mapImporter map[string]*types.Package

func (m mapImporter) Import(path string) (*types.Package, error) {
	if p, ok := m[path]; ok {
		return p, nil
	}
	return nil, &missingImport{path}
}

type missingImport struct{ path string }

func (e *missingImport) Error() string { return "no such import: " + e.path }
