// Copyright 2026 The golang.design Initiative Authors.
// All rights reserved. Use of this source code is governed by
// a BSD-style license that can be found in the LICENSE file.

package emit_test

import (
	"flag"
	"fmt"
	"go/ast"
	"go/constant"
	"go/parser"
	"go/token"
	"go/types"
	"math"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"testing"

	"golang.design/x/accel/internal/kernelc/emit"
	"golang.design/x/accel/internal/kernelc/front"
	"golang.design/x/accel/internal/kernelc/ir"
	"golang.org/x/tools/go/packages"
)

var update = flag.Bool("update", false, "rewrite the golden files")

// normalizeEOL makes a comparison about text rather than about line endings.
func normalizeEOL(s string) string { return strings.ReplaceAll(s, "\r\n", "\n") }

// TestGoldenOutput is spec 004's first testing level: emitted text is
// byte-stable for a fixed input.
//
// The predecessor's equivalent, asserting that existing kernels emit
// byte-identically after a compiler change, caught real regressions and is
// carried forward. A golden is weak evidence about whether the output is right
// and strong evidence about whether it changed, which is the question a
// reviewer of a compiler change actually has.
func TestGoldenOutput(t *testing.T) {
	out := generateCorpus(t)
	golden := filepath.Join("testdata", "testkernels.golden")

	if *update {
		if err := os.MkdirAll("testdata", 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(golden, out, 0o644); err != nil {
			t.Fatal(err)
		}
		t.Log("golden rewritten")
		return
	}

	want, err := os.ReadFile(golden)
	if err != nil {
		t.Fatalf("%v\nrun: go test ./internal/kernelc/emit -update", err)
	}
	// Line endings are normalized before comparing. The golden is checked in
	// with LF and .gitattributes keeps it that way, but a checkout configured
	// otherwise would rewrite it and produce a failure whose diff shows nothing,
	// which is a worse way to learn about a git setting than a one-line
	// normalization.
	if normalizeEOL(string(out)) != normalizeEOL(string(want)) {
		t.Errorf("generated output changed. If the change is intended, rerun with -update "+
			"and review the diff.\n--- got ---\n%s\n--- want ---\n%s", out, want)
	}
}

// TestGeneratedSourceTypeChecks is the level above a golden. Golden text that
// does not compile is worthless, and the emitter is the only thing standing
// between the IR and a package that has to build.
func TestGeneratedSourceTypeChecks(t *testing.T) {
	out := generateCorpus(t)

	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, "generated.go", out, parser.ParseComments)
	if err != nil {
		t.Fatalf("the generated source does not parse: %v\n%s", err, out)
	}

	// The authored sources are type-checked alongside it, because they share a
	// package: the generated lowering calls the helpers they declare and names
	// the types they import.
	files := []*ast.File{f}
	for _, name := range []string{"scale.go", "reduce.go", "scaled.go"} {
		authored, err := os.ReadFile(filepath.Join("..", "..", "testkernels", name))
		if err != nil {
			t.Fatal(err)
		}
		af, err := parser.ParseFile(fset, name, authored, parser.ParseComments)
		if err != nil {
			t.Fatal(err)
		}
		files = append(files, af)
	}

	conf := types.Config{Importer: importerFor(t)}
	if _, err := conf.Check("golang.design/x/accel/internal/testkernels", fset, files, nil); err != nil {
		t.Fatalf("the generated source does not type-check: %v\n%s", err, out)
	}
}

// TestGeneratedShape checks the parts a reader would otherwise have to diff a
// golden to see.
func TestGeneratedShape(t *testing.T) {
	out := string(generateCorpus(t))

	for _, want := range []string{
		"// Code generated by accel-kernel. DO NOT EDIT.",
		"package testkernels",
		"func scaleFlat(t accel.Thread, in []float32, out []float32)",
		"var ScaleKernel = accel.Kernel{",
		`Name:          "Scale"`,
		"WorkgroupSize: accel.ID3{X: 64, Y: 1, Z: 1}",
		`{Name: "in", DType: accel.KernelF32, Access: accel.KernelRead}`,
		`{Name: "out", DType: accel.KernelF32, Access: accel.KernelWrite}`,
		"Generator: accel.KernelABIVersion",
		"accel.KernelSlice[float32](a, 0)",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("the generated file does not contain %q:\n%s", want, out)
		}
	}

	// The rounding point is the reason this is generated rather than called.
	if !strings.Contains(out, "float32(in[i] * float32(2))") {
		t.Errorf("the multiplication has no explicit rounding point: Go may keep an f32 "+
			"intermediate wider, so a lowering without one does not say what the GPU does\n%s", out)
	}

	// It imports only the public package. Generated code lives in a caller's
	// package, and an internal path is importable by this module alone.
	if strings.Contains(out, "internal/kernel") {
		t.Errorf("the generated file names an internal package, so it would compile only "+
			"inside this module:\n%s", out)
	}
}

// TestDigestCoversMoreThanSource is the property that makes freshness mean
// anything: an input that changes what the generated file should contain must
// change the digest, even when the authored source is untouched.
func TestDigestCoversMoreThanSource(t *testing.T) {
	base := corpusKernel(t, "Scale")
	baseline := emit.Digest(base)

	if emit.Digest(base) != baseline {
		t.Fatal("the digest is not stable across calls")
	}

	for _, tc := range []struct {
		name   string
		mutate func(k *ir.Func)
	}{
		{"source", func(k *ir.Func) { k.Source += " " }},
		{"name", func(k *ir.Func) { k.Name = "Other" }},
		{"workgroup extent", func(k *ir.Func) { k.Workgroup[0] = 128 }},
		{"binding name", func(k *ir.Func) { k.Bindings[0].Name = "renamed" }},
		{"binding access", func(k *ir.Func) { k.Bindings[0].Write = true }},
		{"binding element type", func(k *ir.Func) { k.Bindings[0].Type.Elem = &ir.Type{Kind: ir.I32} }},
		{"intrinsic set", func(k *ir.Func) { k.Intrinsics = append(k.Intrinsics, "accel.Thread.LocalID") }},
		{"thread position", func(k *ir.Func) { k.Thread = 1 }},
	} {
		t.Run(tc.name, func(t *testing.T) {
			k := corpusKernel(t, "Scale")
			tc.mutate(k)
			if got := emit.Digest(k); got == baseline {
				t.Errorf("changing the %s left the digest unchanged, so a generated file "+
					"built before the change would still report itself fresh", tc.name)
			}
		})
	}
}

// TestPreimageExplainsAMismatch checks that a freshness failure can say which
// input moved. "The digest differs" leaves a reader guessing between half a
// dozen possibilities.
func TestPreimageExplainsAMismatch(t *testing.T) {
	k := corpusKernel(t, "Scale")
	p := emit.Preimage(k)

	for _, want := range []string{
		"generator/", "abi/kernel/", "abi/intrin/",
		"kernel\tScale", "workgroup\t64\t1\t1",
		"binding\t1\tin\t[]f32\tread", "binding\t2\tout\t[]f32\twrite",
		"intrinsic\taccel.Thread.GlobalID",
		"helpers\t0",
		"source\t",
	} {
		if !strings.Contains(p, want) {
			t.Errorf("the preimage does not carry %q:\n%s", want, p)
		}
	}

	// The version lines come first, so a diff of two preimages shows the
	// cheapest explanation at the top.
	lines := strings.SplitN(p, "\n", 4)
	if !strings.HasPrefix(lines[0], "generator/") {
		t.Errorf("the preimage starts with %q, want the generator version", lines[0])
	}

	// The helpers section exists and is empty, so spec 013 adds lines rather
	// than changing the format and reissuing every committed generated file.
	if !strings.Contains(p, "helpers\t0\n") {
		t.Error("Scale reaches no helper, so its preimage says so")
	}

	// A kernel that does reach one records it by name and by its own source
	// digest, which is what catches a helper edited without its callers being
	// regenerated: the caller's source is untouched and what it compiles to is
	// not.
	withHelpers := emit.Preimage(corpusKernel(t, "SegmentSum"))
	if !strings.Contains(withHelpers, "helpers\t2\n") {
		t.Errorf("SegmentSum reaches two helpers and its preimage does not say so:\n%s", withHelpers)
	}
	for _, name := range []string{"helper\tclampIndex\t", "helper\taccumulate\t"} {
		if !strings.Contains(withHelpers, name) {
			t.Errorf("the preimage omits %q:\n%s", name, withHelpers)
		}
	}
}

// TestEmitterRejectsWhatItCannotLower checks that a node with no lowering is an
// error rather than silently missing output. A generator that drops a statement
// produces a kernel that compiles and computes something else.
func TestEmitterRejectsWhatItCannotLower(t *testing.T) {
	p := token.Pos(1)
	f32 := &ir.Type{Kind: ir.F32}

	for _, tc := range []struct {
		name string
		k    *ir.Func
		want string
	}{
		{
			name: "unknown intrinsic",
			k: kernelWith(ir.NewExprStmt(p,
				ir.NewIntrinsic(p, f32, ir.OpBarrier, ir.NewParam(p, f32, 0, "t", nil), nil))),
			want: "no lowering for intrinsic",
		},
		{
			name: "intrinsic with no receiver",
			k:    kernelWith(ir.NewExprStmt(p, ir.NewIntrinsic(p, f32, ir.OpGlobalID, nil, nil))),
			want: "has no receiver",
		},
		{
			name: "constant with no value",
			k:    kernelWith(ir.NewExprStmt(p, ir.NewConst(p, f32, nil))),
			want: "constant with no value",
		},
		{
			name: "type with no Go spelling",
			k:    kernelWith(ir.NewExprStmt(p, ir.NewConst(p, &ir.Type{Kind: ir.Kind(99)}, nil))),
			want: "constant with no value",
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			_, err := emit.Generate(emit.Package{Name: "p", Kernels: []*ir.Func{tc.k}})
			if err == nil {
				t.Fatal("was emitted")
			}
			if !strings.Contains(err.Error(), tc.want) {
				t.Errorf("error %q does not carry %q", err, tc.want)
			}
		})
	}
}

// kernelWith wraps one statement in an otherwise valid kernel.
func kernelWith(s ir.Stmt) *ir.Func {
	p := token.Pos(1)
	f32s := &ir.Type{Kind: ir.Slice, Elem: &ir.Type{Kind: ir.F32}}
	return &ir.Func{
		Name: "K", Kernel: true, Workgroup: [3]uint32{64, 1, 1}, Thread: 0,
		Params: []*ir.Param{
			ir.NewParam(p, &ir.Type{Kind: ir.Struct, Name: "Thread"}, 0, "t", nil),
			ir.NewParam(p, f32s, 1, "out", nil),
		},
		Bindings: []*ir.Binding{{Name: "out", Index: 1, Type: f32s, Write: true}},
		Body:     ir.NewBlock(p, s),
	}
}

// generateCorpus builds the generated file for the corpus package.
func generateCorpus(t testing.TB) []byte {
	t.Helper()
	kernels := loadCorpus(t)
	for _, k := range kernels {
		k.Digest = emit.Digest(k)
	}
	out, err := emit.Generate(emit.Package{Name: "testkernels", Kernels: kernels})
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	return out
}

// corpusKernel builds the corpus and returns one kernel by name.
//
// By name rather than by index: the corpus has more than one kernel now, and a
// test that reached for the first would start asserting about a different one
// the moment somebody added a file.
func corpusKernel(t testing.TB, name string) *ir.Func {
	t.Helper()
	for _, k := range loadCorpus(t) {
		if k.Name == name {
			return k
		}
	}
	t.Fatalf("the corpus has no kernel named %q", name)
	return nil
}

// loadCorpus type-checks and builds the corpus kernels, freshly each call so a
// mutation in one test cannot reach another.
func loadCorpus(t testing.TB) []*ir.Func {
	t.Helper()
	pkgs, err := front.Load(filepath.Join("..", "..", ".."), "golang.design/x/accel/internal/testkernels")
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	kernels, diags := front.Check(pkgs[0])
	if len(diags) > 0 {
		t.Fatalf("the corpus was rejected:\n%v", diags)
	}
	if len(kernels) == 0 {
		t.Fatal("the corpus has no kernels")
	}
	return kernels
}

var (
	importerOnce sync.Once
	importerVal  types.Importer
)

// importerFor serves the imports a generated kernel file can have: accel,
// kmath for the bounded scalar math, and math for the bit patterns f32
// constants are spelled as.
func importerFor(t testing.TB) types.Importer {
	t.Helper()
	importerOnce.Do(func() {
		cfg := &packages.Config{Mode: packages.NeedName | packages.NeedTypes | packages.NeedDeps | packages.NeedImports}
		pkgs, err := packages.Load(cfg,
			"golang.design/x/accel", "golang.design/x/accel/kmath", "math")
		if err != nil {
			t.Fatalf("loading accel: %v", err)
		}
		byPath := map[string]*types.Package{}
		for _, p := range pkgs {
			byPath[p.PkgPath] = p.Types
		}
		importerVal = mapImporter(byPath)
	})
	return importerVal
}

type mapImporter map[string]*types.Package

func (m mapImporter) Import(path string) (*types.Package, error) {
	if p, ok := m[path]; ok {
		return p, nil
	}
	return nil, &missingImport{path}
}

type missingImport struct{ path string }

func (e *missingImport) Error() string { return "no such import: " + e.path }

// A barrier inside a conditional is refused by position rather than
// mis-lowered.
//
// Loops lower now, because a loop has a back edge to hang a resumption state
// on. A conditional does not: the machine would have to resume inside a branch
// whose predicate it no longer knows. It is refused rather than lowered as a
// no-op, because a no-op barrier is a different program that compiles -- and a
// barrier must sit in workgroup-uniform control flow anyway, so hoisting it out
// of the conditional is always available.
func TestABarrierInsideAConditionalIsRefused(t *testing.T) {
	body := ir.NewBlock(0, ir.NewIf(0,
		ir.NewConst(0, &ir.Type{Kind: ir.Bool}, constant.MakeBool(true)),
		ir.NewBlock(0, ir.NewExprStmt(0,
			ir.NewIntrinsic(0, &ir.Type{Kind: ir.Invalid}, ir.OpBarrier, nil, nil))),
		nil))
	k := &ir.Func{Name: "Branchy", Kernel: true, Cooperative: true, Body: body}

	_, err := emit.Generate(emit.Package{Name: "k", Kernels: []*ir.Func{k}})
	if err == nil {
		t.Fatal("a barrier inside a conditional should be refused")
	}
	for _, want := range []string{"Branchy", "hoist it out of", "018"} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("the message should say %q, got:\n%v", want, err)
		}
	}
}

// A fractional float constant is emitted as the value it is, not as the
// fraction go/constant prints.
//
// go/constant renders an exact rational as "3/4". Wrapped in float32(...) that
// is integer division, so the constant became zero, every comparison against it
// was true, and the kernel computed something else while compiling and running
// cleanly. It survived until a corpus kernel used a fractional threshold, which
// is why this test asserts on the emitted text rather than on a result: a
// result test only catches it for the constants a corpus happens to use.
func TestFractionalConstantsAreNotEmittedAsFractions(t *testing.T) {
	cases := []struct {
		name string
		val  float64
	}{
		{"three quarters", 0.75},
		{"one half", 0.5},
		{"a third, which is not representable", 1.0 / 3},
		{"a negative fraction", -0.125},
		{"a value between two f32s", 1.0000001},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			k := &ir.Func{
				Name: "K", Kernel: true, Workgroup: [3]uint32{1, 1, 1}, Thread: 0,
				Body: ir.NewBlock(0, ir.NewAssign(0,
					ir.NewIndex(0, &ir.Type{Kind: ir.F32},
						ir.NewParam(0, &ir.Type{Kind: ir.Slice, Elem: &ir.Type{Kind: ir.F32}}, 1, "out", nil),
						ir.NewConst(0, &ir.Type{Kind: ir.U32}, constant.MakeInt64(0)), 0),
					ir.NewConst(0, &ir.Type{Kind: ir.F32}, constant.MakeFloat64(c.val)))),
				Params: []*ir.Param{
					ir.NewParam(0, &ir.Type{Kind: ir.ID3Kind}, 0, "t", nil),
					ir.NewParam(0, &ir.Type{Kind: ir.Slice, Elem: &ir.Type{Kind: ir.F32}}, 1, "out", nil),
				},
				Bindings: []*ir.Binding{{Name: "out", Index: 1,
					Type: &ir.Type{Kind: ir.Slice, Elem: &ir.Type{Kind: ir.F32}}, Write: true}},
			}
			out, err := emit.Generate(emit.Package{Name: "k", Kernels: []*ir.Func{k}})
			if err != nil {
				t.Fatalf("generate: %v", err)
			}
			src := string(out)

			// The generated file compiles, which "3/4" also does — so the real
			// assertion is that no constant is spelled as a division.
			if strings.Contains(src, "float32(3/4)") || strings.Contains(src, "/4)") {
				t.Errorf("a constant was emitted as a fraction:\n%s", src)
			}
			// And the emitted bits are the value's, exactly.
			want := fmt.Sprintf("0x%08X", math.Float32bits(float32(c.val)))
			if !strings.Contains(src, want) {
				t.Errorf("the emitted constant should carry the bits %s of %v:\n%s",
					want, c.val, src)
			}
		})
	}
}

// A small whole number is still spelled as one, because a bit pattern where a
// literal would do makes the generated file harder to read for no gain.
func TestWholeNumberConstantsStayReadable(t *testing.T) {
	k := &ir.Func{
		Name: "K", Kernel: true, Workgroup: [3]uint32{1, 1, 1}, Thread: 0,
		Body: ir.NewBlock(0, ir.NewAssign(0,
			ir.NewIndex(0, &ir.Type{Kind: ir.F32},
				ir.NewParam(0, &ir.Type{Kind: ir.Slice, Elem: &ir.Type{Kind: ir.F32}}, 1, "out", nil),
				ir.NewConst(0, &ir.Type{Kind: ir.U32}, constant.MakeInt64(0)), 0),
			ir.NewConst(0, &ir.Type{Kind: ir.F32}, constant.MakeFloat64(2)))),
		Params: []*ir.Param{
			ir.NewParam(0, &ir.Type{Kind: ir.ID3Kind}, 0, "t", nil),
			ir.NewParam(0, &ir.Type{Kind: ir.Slice, Elem: &ir.Type{Kind: ir.F32}}, 1, "out", nil),
		},
		Bindings: []*ir.Binding{{Name: "out", Index: 1,
			Type: &ir.Type{Kind: ir.Slice, Elem: &ir.Type{Kind: ir.F32}}, Write: true}},
	}
	out, err := emit.Generate(emit.Package{Name: "k", Kernels: []*ir.Func{k}})
	if err != nil {
		t.Fatalf("generate: %v", err)
	}
	if !strings.Contains(string(out), "float32(2)") {
		t.Errorf("a whole number should stay a literal:\n%s", out)
	}
}
