// Copyright 2026 The golang.design Initiative Authors.
// All rights reserved. Use of this source code is governed by
// a BSD-style license that can be found in the LICENSE file.

// Package emit turns the typed IR into the generated Go lowering.
//
// # The authored function is not the executable
//
// This is spec 000 decision 5, and it is the reason the whole compiler exists
// in this shape. The CPU backend does not call the function a kernel author
// wrote. It calls this, generated from the same IR every GPU artifact is
// generated from, with an explicit operation at every load, store, and
// arithmetic rounding point.
//
// The cost is a whole class of bug: a mistake in IR construction produces a CPU
// runner and a GPU artifact that agree with each other and disagree with the Go
// program the author read. Differential execution cannot see that, because it is
// wrong identically everywhere. So the authored function is still run, by the
// test at spec 004's fifth level, against this.
//
// The gain is that the CPU backend becomes an oracle rather than a second
// implementation. Two implementations of the same maths disagree in ways nobody
// can attribute; one IR lowered twice disagrees only where the hardware does.
//
// # Why the rounding points are explicit
//
// float32(a * b) rather than a * b. Go permits a compiler to keep an
// intermediate wider than float32, and on a host with FMA it will, so the
// authored function and this one can differ in the last bit. Writing the
// rounding down makes the generated lowering say exactly what the GPU does,
// which is what lets spec 008 bound the difference instead of hoping there
// isn't one.
package emit

import (
	"bytes"
	"fmt"
	"go/constant"
	"go/format"
	"go/token"
	"math"
	"strings"

	"golang.design/x/accel/internal/kernelc/ir"
)

// Package describes what to generate.
type Package struct {
	// Name is the Go package clause the generated file carries.
	Name string

	// Kernels are the kernels found in it, in source order.
	Kernels []*ir.Func

	// Fset resolves the positions the IR carries, so a generated diagnostic can
	// name a line in the author's file rather than an offset only the compiler
	// understands. Optional: without it a barrier is identified by index alone,
	// which is enough to detect a mismatch and not enough to explain one.
	Fset *token.FileSet
}

// Generate produces the generated file's contents, gofmt'd.
func Generate(p Package) ([]byte, error) {

	// The body is emitted first and the header second, because which imports the
	// file needs is only known once every kernel has been lowered.
	var body bytes.Buffer
	e := &emitter{buf: &body, fset: p.Fset}

	// Uniform codecs first, one per type however many kernels take it. A codec
	// belongs to the type rather than to a kernel: two kernels taking the same
	// Params want one encoder, and a caller constructing a value wants one name
	// to write.
	emitted := map[string]bool{}
	for _, k := range p.Kernels {
		for _, u := range k.Uniforms {
			if !emitted[u.TypeName] {
				emitted[u.TypeName] = true
				e.codec(u)
			}
		}
	}

	// Helpers first, and each one once however many kernels reach it. Every
	// target that requires declaration before use gets it for free, and the Go
	// lowering does not care but reads the same way as the others.
	seen := map[*ir.Func]bool{}
	for _, k := range p.Kernels {
		for _, h := range k.Helpers {
			if !seen[h] {
				seen[h] = true
				e.helper(h)
			}
		}
	}
	for _, k := range p.Kernels {
		e.kernel(k)
	}
	e.registry(p.Kernels)
	if e.err != nil {
		return nil, e.err
	}

	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by accel-kernel. DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", p.Name)
	// The imports the body actually used. An unused import does not compile and
	// a missing one does not either, so neither can be guessed: each is
	// recorded while emitting.
	imports := []string{"golang.design/x/accel"}
	if e.needsKMath {
		imports = append(imports, "golang.design/x/accel/kmath")
	}
	if e.needsMath {
		imports = append(imports, "math")
	}
	if len(imports) == 1 {
		fmt.Fprintf(&b, "import %q\n\n", imports[0])
	} else {
		fmt.Fprintf(&b, "import (\n")
		for _, im := range imports {
			fmt.Fprintf(&b, "\t%q\n", im)
		}
		fmt.Fprintf(&b, ")\n\n")
	}
	b.Write(body.Bytes())

	// Formatting the result rather than emitting formatted text is deliberate:
	// a generated file that is not gofmt'd fails the repository's own gate, and
	// keeping the emitter's output pretty by hand is work that buys nothing.
	out, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("accel: the generated source for package %s does not parse: %w\n%s",
			p.Name, err, b.String())
	}
	return out, nil
}

type emitter struct {
	buf *bytes.Buffer
	err error

	// needsKMath records whether the body reached a scalar math intrinsic, so
	// the import is present exactly when it is used. An unused import does not
	// compile, and a missing one does not either, so this cannot be guessed.
	needsKMath bool

	// needsMath records whether a constant had to be spelled as a bit pattern,
	// so the math import is present exactly when it is used.
	needsMath bool

	// frameLocals redirects a local's name to a frame field while emitting the
	// resumable lowering, so that a value declared before a suspension point
	// survives the return. Nil while emitting the flat lowering, which needs no
	// frame because it never suspends. See coop.go.
	frameLocals map[*ir.Local]bool

	// fset resolves IR positions to file:line, or nil.
	fset *token.FileSet

	// sharedIndex maps a shared parameter's name to its position in the
	// kernel's shared list, which is how the tracker keys its shadow bits.
	sharedIndex map[string]int
}

// sharedArray reports whether a value names workgroup-shared storage, and
// which declared array it is.
//
// Which one matters because the tracker keys its shadow bits per array: two
// arrays each have an element zero and conflating them would report a defined
// read as undefined.
func (e *emitter) sharedArray(v ir.Value) (int, bool) {
	p, ok := v.(*ir.Param)
	if !ok || p.Type() == nil || p.Type().Kind != ir.Array {
		return 0, false
	}
	return e.sharedIndex[p.Name], true
}

// local is a local's spelling: its own name, or the frame field standing in for
// it inside the resumable lowering.
func (e *emitter) local(l *ir.Local) string {
	if e.frameLocals[l] {
		return "f." + localField(l)
	}
	return l.Name
}

func (e *emitter) fail(format string, args ...any) {
	if e.err == nil {
		e.err = fmt.Errorf("accel: "+format, args...)
	}
}

func (e *emitter) printf(format string, args ...any) {
	if e.err == nil {
		fmt.Fprintf(e.buf, format, args...)
	}
}

// kernel emits one kernel's lowering, record, and entry point.
func (e *emitter) kernel(k *ir.Func) {
	if k.Cooperative {
		e.cooperativeKernel(k)
		return
	}
	lower := lowerName(k.Name)

	e.printf("// %s is the generated flat lowering of %s.\n", lower, k.Name)
	e.printf("//\n")
	e.printf("// It is what the CPU backend runs. The authored %s is never registered as\n", k.Name)
	e.printf("// an executable: it supplies the typed source this was built from, and it is\n")
	e.printf("// run only by the test that checks the two agree.\n")
	e.printf("func %s(", lower)
	for i, p := range k.Params {
		if i > 0 {
			e.printf(", ")
		}
		e.printf("%s %s", p.Name, e.goType(p.Type()))
	}
	e.printf(") {\n")
	e.block(k.Body, 1)
	e.printf("}\n\n")

	e.printf("// %s is the compiled form of %s.\n", k.Name+"Kernel", k.Name)
	e.printf("var %s = accel.Kernel{\n", k.Name+"Kernel")
	e.printf("\tName: %q,\n", k.Name)
	e.printf("\tWorkgroupSize: accel.ID3{X: %d, Y: %d, Z: %d},\n",
		k.Workgroup[0], k.Workgroup[1], k.Workgroup[2])
	e.printf("\tBindings: []accel.KernelBinding{\n")
	for _, b := range k.Bindings {
		e.printf("\t\t{Name: %q, DType: %s, Access: %s},\n", b.Name, e.dtype(b.Type), access(b))
	}
	e.printf("\t},\n")
	e.printf("\tDigest: %q,\n", k.Digest)
	e.printf("\tGenerator: accel.KernelABIVersion,\n")
	if k.Caps != 0 {
		e.printf("\tCaps: %d,\n", k.Caps)
	}
	e.mslArtifact(k)
	e.uniformRecords(k)
	e.printf("\tFlat: func(t accel.Thread, a accel.KernelArgs) {\n")
	e.printf("\t\t%s(t", lower)
	// Parameters are passed in signature order, which interleaves uniforms and
	// bindings however the author wrote them. The argument set is indexed the
	// same way, so a caller supplies them in the order the signature reads.
	slot := 0
	uniformSlot := 0
	for _, p := range k.Params {
		if p.Index == k.Thread {
			continue
		}
		if u := uniformAt(k, p.Index); u != nil {
			e.printf(", accel.KernelUniformValue[%s](a, %d)", u.TypeName, uniformSlot)
			uniformSlot++
			continue
		}
		e.printf(", accel.KernelSlice[%s](a, %d)", e.goType(p.Type().Elem), slot)
		slot++
	}
	e.printf(")\n")
	e.printf("\t},\n")
	e.printf("}\n\n")
}

// uniformRecords emits the by-value parameter list, each with its encoder.
//
// The encoder is closed over here rather than looked up at run time because
// only generation knows which codec belongs to which parameter. A backend holds
// the value as an any and needs std140 bytes; without this it would have to
// reflect over the Go struct, which would be a second layout implementation
// beside the codec and would disagree with it eventually.
func (e *emitter) uniformRecords(k *ir.Func) {
	if len(k.Uniforms) == 0 {
		return
	}
	e.printf("\tUniforms: []accel.KernelUniform{\n")
	for _, u := range k.Uniforms {
		e.printf("\t\t{Name: %q, Type: %q, Size: %d, Encode: func(dst []byte, v any) error {\n",
			u.Name, u.TypeName, u.Size)
		e.printf("\t\t\treturn accel.EncodeKernelUniform(dst, v, %sCodec{}.Encode)\n", u.TypeName)
		e.printf("\t\t}},\n")
	}
	e.printf("\t},\n")
}

// registry emits the package's kernels as one slice.
//
// It exists so that a test or a selection pass can iterate the corpus without
// keeping a list beside it. A hand-maintained list goes stale the moment the
// package gains a kernel, and the failure is silence: the new kernel looks
// exactly like one that passed.
func (e *emitter) registry(kernels []*ir.Func) {
	if len(kernels) == 0 {
		return
	}
	e.printf("// Kernels is every kernel this package generated, in source order.\n")
	e.printf("//\n")
	e.printf("// Generated rather than written, so that a pass over the whole corpus cannot\n")
	e.printf("// silently miss a kernel somebody added.\n")
	e.printf("var Kernels = []*accel.Kernel{\n")
	for _, k := range kernels {
		e.printf("\t&%sKernel,\n", k.Name)
	}
	e.printf("}\n\n")
}

// mslArtifact emits the Metal target's source, when this kernel is inside the
// subset that target can lower.
//
// A kernel outside it emits nothing rather than failing the whole generation.
// The MSL subset is narrower than the Go one by construction and widens over
// specs/022-msl-target.md, so a refusal here is a statement about how far the
// Metal target has got, not about whether the kernel is legal. What makes the
// gap visible rather than silent is the golden: a kernel losing its MSL shows up
// as a diff.
func (e *emitter) mslArtifact(k *ir.Func) {
	src, err := MSL(k)
	if err != nil {
		return
	}
	if strings.Contains(src, "`") {
		e.fail("the MSL for %s contains a backquote, which a raw string literal cannot hold", k.Name)
		return
	}
	e.printf("\tMSL: `%s`,\n", src)
}

// codec emits a uniform type's std140 encoder.
//
// The encoder is a list of writes at fixed offsets, and the offsets came from
// the layout rather than from Go's own struct. That separation is the whole
// point: a caller's struct declares no padding field, and an unsafe cast would
// be silently correct until the first three-component vector.
func (e *emitter) codec(u *ir.Uniform) {
	name := u.TypeName + "Codec"

	e.printf("// %s is the generated std140 codec for %s.\n", name, u.TypeName)
	e.printf("//\n")
	e.printf("// The offsets are std140's, not Go's. A caller never spells one.\n")
	e.printf("type %s struct{}\n\n", name)

	e.printf("// %sBlockSize is the encoded size of a %s block, in bytes.\n", u.TypeName, u.TypeName)
	e.printf("const %sBlockSize = %d\n\n", u.TypeName, u.Size)

	e.printf("// EncodedSize reports the std140 block size.\n")
	e.printf("func (%s) EncodedSize() int { return %sBlockSize }\n\n", name, u.TypeName)

	e.printf("// Encode writes value into dst in std140 layout.\n")
	e.printf("func (%s) Encode(dst []byte, value %s) error {\n", name, u.TypeName)
	e.printf("\tw := accel.NewUniformWriter(dst)\n")
	for _, f := range u.Fields {
		e.codecField(f, "value."+f.Name, f.Offset, 1)
	}
	e.printf("\treturn w.Err()\n")
	e.printf("}\n\n")
}

// codecField emits the writes for one member.
func (e *emitter) codecField(f ir.UniformField, expr string, offset, depth int) {
	write := func(off int, val string) {
		e.printf("%sw.%s(%d, %s)\n", indent(depth), writerMethod(f.Scalar), off, val)
	}

	switch f.Kind {
	case "scalar":
		write(offset, expr)

	case "vector":
		// A vector's components are adjacent, unlike an array's.
		for i := range f.Len {
			write(offset+i*4, fmt.Sprintf("%s[%d]", expr, i))
		}

	case "array":
		// Each element starts a fresh sixteen-byte slot, which is the padding
		// that makes an array of 64 floats occupy 1024 bytes.
		for i := range f.Len {
			write(offset+i*f.Stride, fmt.Sprintf("%s[%d]", expr, i))
		}

	case "matrix":
		// A matrix is an array of column vectors, so each column starts a slot
		// and its components are adjacent within it.
		for col := range f.Len {
			base := offset + col*f.Stride
			for row := range f.Len {
				write(base+row*4, fmt.Sprintf("%s[%d][%d]", expr, col, row))
			}
		}

	default:
		e.fail("no encoder for uniform member %s of kind %q", f.Name, f.Kind)
	}
}

// writerMethod is the UniformWriter method for a scalar type.
func writerMethod(scalar string) string {
	switch scalar {
	case "float32":
		return "F32"
	case "int32":
		return "I32"
	case "uint32":
		return "U32"
	}
	return "F32"
}

// helper emits one helper's lowering.
func (e *emitter) helper(h *ir.Func) {
	name := lowerName(h.Name)
	e.printf("// %s is the generated lowering of the helper %s.\n", name, h.Name)
	e.printf("func %s(", name)
	for i, p := range h.Params {
		if i > 0 {
			e.printf(", ")
		}
		e.printf("%s %s", p.Name, e.goType(p.Type()))
	}
	e.printf(")")
	if h.Result != nil {
		e.printf(" %s", e.goType(h.Result))
	}
	e.printf(" {\n")
	e.block(h.Body, 1)
	e.printf("}\n\n")
}

// uniformAt reports the uniform at a parameter index, if there is one.
func uniformAt(k *ir.Func, index int) *ir.Uniform {
	for _, u := range k.Uniforms {
		if u.Index == index {
			return u
		}
	}
	return nil
}

// lowerName is the unexported name a kernel's lowering takes.
func lowerName(name string) string {
	if name == "" {
		return "flat"
	}
	return strings.ToLower(name[:1]) + name[1:] + "Flat"
}

func access(b *ir.Binding) string {
	switch {
	case b.Read && b.Write:
		return "accel.KernelRead | accel.KernelWrite"
	case b.Write:
		return "accel.KernelWrite"
	default:
		return "accel.KernelRead"
	}
}

// block emits a statement list at the given indent.
func (e *emitter) block(b *ir.Block, depth int) {
	for _, s := range b.List {
		e.stmt(s, depth)
	}
}

func indent(depth int) string { return strings.Repeat("\t", depth) }

// stmt emits one statement.
func (e *emitter) stmt(s ir.Stmt, depth int) {
	switch s := s.(type) {
	case *ir.Block:
		e.printf("%s{\n", indent(depth))
		e.block(s, depth+1)
		e.printf("%s}\n", indent(depth))

	case *ir.Declare:
		if e.frameLocals[s.Local] {
			// The frame already declares it, so this is an assignment. Keeping
			// the `var` would shadow the field and lose the value at the next
			// suspension point, which is a wrong answer rather than a compile
			// error.
			e.printf("%s%s = ", indent(depth), e.local(s.Local))
			e.value(s.Init)
			e.printf("\n")
			break
		}
		e.printf("%svar %s %s = ", indent(depth), s.Local.Name, e.goType(s.Local.Type()))
		e.value(s.Init)
		e.printf("\n")

	case *ir.Assign:
		// A store into shared memory is announced to the tracker before it
		// happens, so a later read knows the element is defined. Nothing outside
		// the kernel can see a shared access -- it is an ordinary slice index in
		// generated Go -- which is why the lowering carries the instrumentation
		// rather than the runtime watching for it.
		if idx, ok := s.LHS.(*ir.IndexExpr); ok {
			if array, isShared := e.sharedArray(idx.X); isShared {
				e.printf("%str.Write(%d, int(", indent(depth), array)
				e.value(idx.Index)
				e.printf("))\n")
				// The destination's own index is not a read, so it is emitted
				// uninstrumented. Without this every store would also report a
				// read of the element it is about to define, which is a
				// diagnostic that fires on every correct kernel.
				e.printf("%s", indent(depth))
				e.value(idx.X)
				e.printf("[")
				e.value(idx.Index)
				e.printf("] = ")
				e.rounded(s.RHS)
				e.printf("\n")
				break
			}
		}
		e.printf("%s", indent(depth))
		e.value(s.LHS)
		e.printf(" = ")
		e.rounded(s.RHS)
		e.printf("\n")

	case *ir.ExprStmt:
		e.printf("%s", indent(depth))
		e.value(s.X)
		e.printf("\n")

	case *ir.If:
		e.printf("%sif ", indent(depth))
		e.value(s.Cond)
		e.printf(" {\n")
		e.block(s.Then, depth+1)
		if s.Else == nil {
			e.printf("%s}\n", indent(depth))
			return
		}
		e.printf("%s} else ", indent(depth))
		switch els := s.Else.(type) {
		case *ir.Block:
			e.printf("{\n")
			e.block(els, depth+1)
			e.printf("%s}\n", indent(depth))
		default:
			e.printf("\n")
			e.stmt(s.Else, depth)
		}

	case *ir.For:
		e.forStmt(s, depth)

	case *ir.Break:
		e.printf("%sbreak\n", indent(depth))

	case *ir.Continue:
		e.printf("%scontinue\n", indent(depth))

	case *ir.Return:
		if s.Value == nil {
			e.printf("%sreturn\n", indent(depth))
			return
		}
		e.printf("%sreturn ", indent(depth))
		e.rounded(s.Value)
		e.printf("\n")

	default:
		e.fail("no lowering for statement %T", s)
	}
}

// forStmt emits a loop.
//
// A loop whose init declares a variable is wrapped in a block, and the
// declaration is hoisted out of the clause. Go's for-init takes a simple
// statement and `var x T = v` is not one, so the alternative is emitting
// `x := v` in the clause. That would work and it would throw away a check worth
// keeping: `var x T = v` is a compile error when the IR says a local has one
// type and its initializer another, and `:=` silently takes whatever the
// initializer happened to be. The wrapping block keeps the scope exactly as
// narrow as the loop's, so nothing else changes.
func (e *emitter) forStmt(s *ir.For, depth int) {
	body := depth
	if decl, ok := s.Init.(*ir.Declare); ok {
		e.printf("%s{\n", indent(depth))
		body = depth + 1
		e.stmt(decl, body)
	}

	e.printf("%sfor ", indent(body))
	switch {
	case s.Init != nil || s.Post != nil:
		e.printf("; ")
		if s.Cond != nil {
			e.value(s.Cond)
		}
		e.printf("; ")
		e.inline(s.Post)
	case s.Cond != nil:
		e.value(s.Cond)
	}
	e.printf(" {\n")
	e.block(s.Body, body+1)
	e.printf("%s}\n", indent(body))

	if body != depth {
		e.printf("%s}\n", indent(depth))
	}
}

// inline emits a statement in the single-line form a for clause takes, which is
// a simple statement and never a declaration.
func (e *emitter) inline(s ir.Stmt) {
	switch s := s.(type) {
	case nil:
	case *ir.Assign:
		e.value(s.LHS)
		e.printf(" = ")
		e.rounded(s.RHS)
	default:
		e.fail("no lowering for %T in a for clause: it takes a simple statement", s)
	}
}

// rounded emits a value with the explicit rounding point its type requires.
//
// This is the whole point of generating rather than calling. Go permits an
// intermediate float32 expression to be evaluated wider, and on a host with FMA
// it is, so a * b + c can differ from the GPU in the last bit. Naming the
// rounding makes the lowering say what the GPU does. Integer arithmetic has no
// such freedom and is left alone, because a redundant conversion there is noise
// in every generated file.
func (e *emitter) rounded(v ir.Value) {
	if !needsRounding(v) {
		e.value(v)
		return
	}
	// A binary operation already parenthesizes itself, so naming the conversion
	// in front of it is enough. Wrapping again would double the parentheses in
	// every arithmetic expression in every generated file, which is noise a
	// reader has to see past to check the lowering.
	if _, isBinary := v.(*ir.Binary); isBinary {
		e.printf("float32")
		e.value(v)
		return
	}
	e.printf("float32(")
	e.value(v)
	e.printf(")")
}

// needsRounding reports whether a value is f32 arithmetic whose intermediate a
// compiler may keep wider.
func needsRounding(v ir.Value) bool {
	if v.Type() == nil || v.Type().Kind != ir.F32 {
		return false
	}
	switch v.(type) {
	case *ir.Binary, *ir.Unary:
		return true
	}
	return false
}

// value emits an expression.
func (e *emitter) value(v ir.Value) {
	switch v := v.(type) {
	case *ir.Const:
		e.constant(v)

	case *ir.Param:
		e.printf("%s", v.Name)

	case *ir.Local:
		e.printf("%s", e.local(v))

	case *ir.FieldSel:
		// An id component and a uniform member are both an ordinary field
		// selection in the Go lowering. The difference is the layout, and the
		// layout is the codec's business, not the body's.
		e.value(v.X)
		e.printf(".%s", v.Name)

	case *ir.IndexExpr:
		// A load from shared memory is announced through a helper that returns
		// the index, so the call sits inside the expression rather than needing
		// a statement: a read can appear anywhere a value can.
		if array, isShared := e.sharedArray(v.X); isShared {
			e.value(v.X)
			e.printf("[tr.ReadAt(%d, int(", array)
			e.value(v.Index)
			e.printf("))]")
			break
		}
		e.value(v.X)
		e.printf("[")
		e.value(v.Index)
		e.printf("]")

	case *ir.Unary:
		e.printf("%s", v.Op)
		e.value(v.X)

	case *ir.Binary:
		e.printf("(")
		e.rounded(v.X)
		e.printf(" %s ", v.Op)
		e.rounded(v.Y)
		e.printf(")")

	case *ir.Convert:
		// A conversion to f32 is itself the rounding point, so wrapping its
		// operand would be a redundant conversion in every generated file. A
		// conversion to anything else is not: an f32 product whose intermediate
		// stayed wider truncates to a different integer.
		e.printf("%s(", e.goType(v.Type()))
		if v.Type().Kind == ir.F32 {
			e.value(v.X)
		} else {
			e.rounded(v.X)
		}
		e.printf(")")

	case *ir.Len:
		e.printf("int32(len(")
		e.value(v.X)
		e.printf("))")

	case *ir.IntrinsicCall:
		e.intrinsic(v)

	case *ir.Call:
		e.printf("%s(", lowerName(v.Callee.Name))
		for i, a := range v.Args {
			if i > 0 {
				e.printf(", ")
			}
			e.rounded(a)
		}
		e.printf(")")

	default:
		e.fail("no lowering for value %T", v)
	}
}

// constant emits a literal in its resolved type.
//
// In its resolved type, which is where the GLSL integer-literal divergence is
// settled at the root: the emitter knows whether the 2 in gid*2 is u32 or f32
// and spells it accordingly, rather than coercing an id to int to keep the
// literal legal.
func (e *emitter) constant(c *ir.Const) {
	if c.Val == nil {
		e.fail("a constant with no value at %v", c.Pos())
		return
	}
	switch c.Type().Kind {
	case ir.Bool:
		e.printf("%s", c.Val.String())
	case ir.F32:
		e.f32Constant(c)
	default:
		e.printf("%s(%s)", e.goType(c.Type()), c.Val.String())
	}
}

// f32Constant emits a float constant as the value it rounds to, spelled exactly.
//
// # Why not ExactString
//
// go/constant renders an exact rational as a fraction: 0.75 prints as "3/4".
// Wrapped in float32(...) that is *integer division*, so the constant becomes
// zero and every comparison against it is true. The kernel compiles, runs, and
// computes something else — which is the failure this project spends its whole
// diagnostics budget avoiding, and it survived until a corpus kernel used a
// fractional threshold.
//
// # Why the bit pattern rather than a decimal
//
// A decimal has to round-trip through the Go parser, and a value at the
// boundary between two f32s depends on that parser rounding the way this one
// did. The bit pattern does not round-trip at all: it names the f32 exactly,
// which is what specs/008-numerics.md means by every language-level rounding
// point being emitted. The decimal goes in a comment, since a reader needs the
// number and the compiler needs the bits.
func (e *emitter) f32Constant(c *ir.Const) {
	f, exact := constant.Float32Val(c.Val)
	bits := math.Float32bits(f)
	switch {
	case math.IsInf(float64(f), 0) || f != f:
		// An infinity or NaN has no literal spelling that survives a parser.
		e.printf("math.Float32frombits(0x%08X)", bits)
		e.needsMath = true
	case exact && f == float32(int32(f)) && math.Abs(float64(f)) < 1<<23:
		// A small whole number is exact as a literal and reads better than a
		// bit pattern. The bound is where f32 stops representing every integer.
		e.printf("float32(%d)", int32(f))
	default:
		e.printf("math.Float32frombits(0x%08X /* %v */)", bits, f)
		e.needsMath = true
	}
}

// intrinsic emits a thread-id accessor.
func (e *emitter) intrinsic(v *ir.IntrinsicCall) {
	// Narrow conversions. The widening direction is a method on the value and
	// the narrowing direction is a function on the root package, which is what
	// an author writes and therefore what the lowering says.
	switch v.Op {
	case ir.OpF16ToF32, ir.OpBF16ToF32:
		if v.Recv == nil {
			e.fail("conversion %v has no value to convert at %v", v.Op, v.Pos())
			return
		}
		e.value(v.Recv)
		e.printf(".F32()")
		return
	case ir.OpF32ToF16, ir.OpF32ToBF16:
		name := "ToFloat16"
		if v.Op == ir.OpF32ToBF16 {
			name = "ToBFloat16"
		}
		if len(v.Args) != 1 {
			e.fail("%s takes one value at %v", name, v.Pos())
			return
		}
		e.printf("accel.%s(", name)
		e.rounded(v.Args[0])
		e.printf(")")
		return
	}

	// A subgroup id accessor is an ordinary method on the thread: it reads this
	// invocation's own position and combines nothing, so it needs no
	// rendezvous. The rendezvous operations never reach here -- the state split
	// turns each into a pair of states.
	switch v.Op {
	case ir.OpSubgroupSize, ir.OpSubgroupID, ir.OpSubgroupInvocationID:
		if v.Recv == nil {
			e.fail("%v has no receiver at %v", v.Op, v.Pos())
			return
		}
		e.value(v.Recv)
		e.printf(".%v()", v.Op)
		return
	}

	// Atomics lower to the same functions the authored kernel calls, so the two
	// agree by construction on this backend. A GPU backend emits its own
	// instruction instead, which is the whole reason these are intrinsics
	// rather than ordinary helper calls.
	if fn, ok := atomicFunc[v.Op]; ok {
		e.printf("accel.%s(", fn)
		for i, a := range v.Args {
			if i > 0 {
				e.printf(", ")
			}
			// Not rounded: an atomic's arguments are a buffer, an index, and a
			// value, and wrapping a slice in a float conversion does not
			// compile. The one f32 atomic rounds inside the operation.
			e.value(a)
		}
		e.printf(")")
		return
	}

	if fn, ok := intrinsicFunc[v.Op]; ok {
		e.needsKMath = true
		e.printf("kmath.%s(", fn)
		for i, a := range v.Args {
			if i > 0 {
				e.printf(", ")
			}
			e.rounded(a)
		}
		e.printf(")")
		return
	}

	name, ok := intrinsicMethod[v.Op]
	if !ok {
		e.fail("no lowering for intrinsic %v at %v", v.Op, v.Pos())
		return
	}
	if v.Recv == nil {
		e.fail("intrinsic %v has no receiver at %v", v.Op, v.Pos())
		return
	}
	e.value(v.Recv)
	e.printf(".%s(", name)
	for i, a := range v.Args {
		if i > 0 {
			e.printf(", ")
		}
		e.rounded(a)
	}
	e.printf(")")
}

// intrinsicMethod maps an opcode back to the method the runtime provides.
//
// The generated code calls accel.Thread's own accessors rather than reaching
// into the ids directly, because the ids are the backend's to own: at M4 a
// Thread carries rendezvous state, and a lowering that had copied the ids out
// would be holding a stale half of it.
var intrinsicMethod = map[ir.Opcode]string{
	ir.OpGlobalID:    "GlobalID",
	ir.OpLocalID:     "LocalID",
	ir.OpGroupID:     "GroupID",
	ir.OpGlobalIndex: "GlobalIndex",
	ir.OpLocalIndex:  "LocalIndex",
	ir.OpGroupIndex:  "GroupIndex",
}

// intrinsicFunc maps an opcode to the free function the Go lowering calls.
//
// The generated code calls accel/kmath rather than math, because that package
// *is* the reference these operations are defined against. Calling math would
// make the CPU lowering agree with Go's library and the GPU artifacts agree
// with their drivers, with nothing saying the two are the same operation.
var intrinsicFunc = map[ir.Opcode]string{
	ir.OpSqrt:  "Sqrt",
	ir.OpRSqrt: "RSqrt",
	ir.OpExp:   "Exp",
	ir.OpLog:   "Log",
	ir.OpSin:   "Sin",
	ir.OpCos:   "Cos",
	ir.OpTanh:  "Tanh",
	ir.OpAbs:   "Abs",
	ir.OpMin:   "Min",
	ir.OpMax:   "Max",
}

// atomicFunc is each atomic's spelling on the root package, which is what an
// author writes and therefore what the lowering says.
var atomicFunc = map[ir.Opcode]string{
	ir.OpAtomicAddU32:             "AddU32",
	ir.OpAtomicAddI32:             "AddI32",
	ir.OpAtomicSubU32:             "SubU32",
	ir.OpAtomicSubI32:             "SubI32",
	ir.OpAtomicMinU32:             "MinU32",
	ir.OpAtomicMinI32:             "MinI32",
	ir.OpAtomicMaxU32:             "MaxU32",
	ir.OpAtomicMaxI32:             "MaxI32",
	ir.OpAtomicAndU32:             "AndU32",
	ir.OpAtomicOrU32:              "OrU32",
	ir.OpAtomicXorU32:             "XorU32",
	ir.OpAtomicExchangeU32:        "ExchangeU32",
	ir.OpAtomicExchangeI32:        "ExchangeI32",
	ir.OpAtomicCompareExchangeU32: "CompareExchangeU32",
	ir.OpAtomicCompareExchangeI32: "CompareExchangeI32",
	ir.OpAtomicAddF32:             "AddF32",
}

// goType is the Go spelling of an IR type.
func (e *emitter) goType(t *ir.Type) string {
	if t == nil {
		e.fail("a value with no type")
		return "invalid"
	}
	switch t.Kind {
	case ir.Bool:
		return "bool"
	case ir.I32:
		return "int32"
	case ir.U32:
		return "uint32"
	case ir.F32:
		return "float32"
	case ir.I8:
		return "int8"
	case ir.U8:
		return "uint8"
	case ir.F16:
		// A 16-bit float is stored, never computed. The type carries no
		// operators, so the conversion to f32 is explicit in the kernel's own
		// source rather than something the emitter inserts.
		return "accel.Float16"
	case ir.BF16:
		return "accel.BFloat16"
	case ir.ID3Kind:
		return "accel.ID3"
	case ir.Struct:
		if t.Name == "Thread" {
			return "accel.Thread"
		}
		return t.Name
	case ir.Slice:
		return "[]" + e.goType(t.Elem)
	case ir.Array:
		return fmt.Sprintf("[%d]%s", t.Len, e.goType(t.Elem))
	}
	e.fail("no Go spelling for type %v", t)
	return "invalid"
}

// dtype is the generated spelling of a binding's element type.
func (e *emitter) dtype(t *ir.Type) string {
	if t == nil || t.Elem == nil {
		e.fail("a binding with no element type")
		return "accel.KernelF32"
	}
	switch t.Elem.Kind {
	case ir.F32:
		return "accel.KernelF32"
	case ir.I32:
		return "accel.KernelI32"
	case ir.U32:
		return "accel.KernelU32"
	case ir.I8:
		return "accel.KernelI8"
	case ir.U8:
		return "accel.KernelU8"
	case ir.F16:
		return "accel.KernelF16"
	case ir.BF16:
		return "accel.KernelBF16"
	}
	e.fail("no dtype for binding element %v", t.Elem)
	return "accel.KernelF32"
}
